/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vérifier la disponibilité de l'API */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vérifier que le processus HTTP est vivant */
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vérifier PostgreSQL et le worker de génération */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/generations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lister les demandes de génération
         * @description Retourne l'historique paginé du propriétaire authentifié, y compris les demandes en attente de clarification ou sans cours créé.
         */
        get: operations["listGenerationRequests"];
        put?: never;
        /**
         * Démarrer une génération complète
         * @description Persiste la demande et enfile un job d'analyse. La réponse 202 est immédiate. Si l'analyse requiert des précisions, la pipeline passe à awaiting_clarification et le client doit appeler l'URL fournie dans actionRequired. Dans le cas contraire, le job d'architecture est automatiquement enfilé.
         */
        post: operations["startFullGeneration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/generations/{requestID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Supprimer une demande et toutes ses données
         * @description Supprime atomiquement la demande possédée par l'utilisateur, ses jobs, son cours et tout le graphe pédagogique par cascade PostgreSQL.
         */
        delete: operations["deleteGenerationRequest"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/generations/{requestID}/clarifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Soumettre les clarifications et continuer la génération
         * @description Valide les réponses contre les questions persistées, confirme le brief puis enfile atomiquement le job d'architecture. selectedValues doit utiliser les champs value reçus dans clarificationQuestions. Un rejeu strictement identique est idempotent.
         */
        post: operations["submitGenerationClarifications"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/generations/{requestID}/structure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enfiler la génération de la structure
         * @description Confirme le brief s'il ne l'est pas encore et enfile l'architecture, les modules et les plans de leçons. Cette opération ne génère pas le contenu détaillé des leçons et refuse une demande encore en attente de clarification.
         */
        post: operations["generateCourseStructure"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/generations/{requestID}/structure/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Relancer uniquement la structure
         * @description Disponible seulement pour une pipeline failed dont currentStep correspond à architecture_generation ou lesson_plan_generation. Les données partielles de structure sont supprimées avant l'enfilage du nouveau job.
         */
        post: operations["retryCourseStructure"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/generations/lessons/{lessonID}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enfiler la génération du contenu d'une leçon
         * @description Enfile un job ciblé qui remplace atomiquement le Markdown, les exercices et les quiz persistés de la leçon.
         */
        post: operations["generateLessonContent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/generations/modules/{moduleID}/contents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enfiler le contenu de toutes les leçons d'un module
         * @description Enfile un job parent de module qui orchestre la génération du contenu de chaque leçon du module.
         */
        post: operations["generateModuleLessonContents"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/generations/{requestID}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consulter l'état fonctionnel d'une génération
         * @description Endpoint de polling principal. actionRequired indique au frontend qu'une soumission de clarifications est nécessaire.
         */
        get: operations["getGenerationStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/generations/{requestID}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Récupérer le résultat complet d'une génération
         * @description Retourne la demande et le graphe complet course/modules/lessons/activities. Tant que la pipeline n'est pas completed, l'API retourne 409.
         */
        get: operations["getGenerationResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/generations/{requestID}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Relancer une génération échouée
         * @description Relance la pipeline durable à partir de son checkpoint. Seules les générations failed sont éligibles.
         */
        post: operations["retryFullGeneration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/generations/{requestID}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrouver les jobs d'une generation
         * @description Retourne les etats publics des jobs de la demande appartenant a l'utilisateur connecte, pour reprendre le suivi apres rechargement. Les payloads internes ne sont pas exposes.
         */
        get: operations["listGenerationJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/generation-jobs/{jobID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consulter l'état technique d'un job
         * @description Expose le type, les tentatives, le verrou et l'erreur terminale d'un job asynchrone.
         */
        get: operations["getGenerationJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lister les formations
         * @description Retourne une page de formations triées. pageSize est normalisé par le backend et limité à 100.
         */
        get: operations["listCourses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{courseID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Récupérer une formation complète
         * @description Charge le cours et toutes ses relations : modules, leçons, exercices et quiz.
         */
        get: operations["getCourse"];
        put?: never;
        post?: never;
        /**
         * Supprimer une formation
         * @description Supprime le cours et ses relations selon les contraintes de cascade PostgreSQL.
         */
        delete: operations["deleteCourse"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{courseID}/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lister les modules d'une formation */
        get: operations["listCourseModules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/modules/{moduleID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Récupérer un module */
        get: operations["getModule"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/modules/{moduleID}/lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lister les leçons d'un module */
        get: operations["listModuleLessons"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons/{lessonID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Récupérer une leçon complète
         * @description Retourne le Markdown, les exercices structurés et les quiz de la leçon.
         */
        get: operations["getLesson"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons/{lessonID}/solutions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Révéler les solutions d'une leçon
         * @description Retourne explicitement les corrections des exercices et les réponses des quiz. Les endpoints ordinaires n'exposent jamais ces données.
         */
        get: operations["getLessonSolutions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
        };
        ReadinessResponse: {
            /** @enum {string} */
            status: "ok" | "not_ready";
            /** @enum {string} */
            reason?: "worker_disabled" | "database_unavailable";
        };
        ErrorResponse: {
            /** @description Code stable exploitable par le client. */
            code: string;
            /** @description Message public sans détail interne. */
            message: string;
        };
        StartGenerationRequest: {
            prompt: string;
        };
        GenerateStructureRequest: {
            title: string;
            synopsis: string;
            currentLevel: components["schemas"]["Level"];
            targetLevel: components["schemas"]["Level"];
            goals: string[];
            language: components["schemas"]["Language"];
        };
        SubmitClarificationsRequest: {
            answers: components["schemas"]["ClarificationAnswerRequest"][];
            title: string;
            synopsis: string;
            language: components["schemas"]["Language"];
        };
        ClarificationAnswerRequest: {
            /** @enum {string} */
            questionId: "goals" | "currentLevel" | "targetLevel";
            selectedValues: string[];
        };
        GenerationStartedResponse: {
            /** Format: uuid */
            jobId: string;
            /** Format: uuid */
            requestId: string;
            status: components["schemas"]["PipelineStatus"];
            jobStatus: components["schemas"]["JobStatus"];
            /** Format: uri-reference */
            statusUrl: string;
            /** Format: uri-reference */
            jobStatusUrl: string;
            /** Format: uri-reference */
            resultUrl: string;
        };
        GenerationPageResponse: {
            items: components["schemas"]["GenerationSummaryResponse"][];
            page: number;
            pageSize: number;
            totalItems: number;
            totalPages: number;
            hasNext: boolean;
            hasPrevious: boolean;
        };
        GenerationSummaryResponse: {
            /** Format: uuid */
            requestId: string;
            /** Format: uuid */
            courseId: string | null;
            initialUserPrompt: string;
            title: string;
            pipelineStatus: components["schemas"]["PipelineStatus"];
            courseStatus: components["schemas"]["CourseStatus"] | null;
            currentStep: string | null;
            progressPercent: number;
            isOutOfScope: boolean;
            failureMessage: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        GenerationJobResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            requestId: string;
            /** Format: uuid */
            parentJobId: string | null;
            kind: components["schemas"]["JobKind"];
            status: components["schemas"]["JobStatus"];
            /** Format: uuid */
            targetId: string | null;
            priority: number;
            attemptCount: number;
            maxAttempts: number;
            /** Format: date-time */
            availableAt: string;
            /** Format: date-time */
            lockedUntil: string | null;
            /** Format: date-time */
            startedAt: string | null;
            /** Format: date-time */
            completedAt: string | null;
            lastErrorCode: string | null;
            lastErrorMessage: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        GenerationStatusResponse: {
            /** Format: uuid */
            requestId: string;
            /** Format: uuid */
            courseId: string | null;
            pipelineStatus: components["schemas"]["PipelineStatus"];
            courseStatus: components["schemas"]["CourseStatus"] | null;
            currentStep: string | null;
            progressPercent: number;
            failureMessage: string | null;
            isOutOfScope: boolean;
            errorMessage: string | null;
            warningMessage: string | null;
            suggestedTitle: string | null;
            shortSynopsis: string | null;
            detectedCurrentLevel: components["schemas"]["Level"] | null;
            detectedTargetLevel: components["schemas"]["Level"] | null;
            detectedGoal: string | null;
            detectedLanguage: components["schemas"]["Language"] | null;
            clarificationQuestions: components["schemas"]["ClarificationQuestionResponse"][];
            actionRequired: components["schemas"]["GenerationActionRequiredResponse"] | null;
        };
        GenerationActionRequiredResponse: {
            /** @enum {string} */
            type: "submit_clarifications";
            /** Format: uri-reference */
            url: string;
        };
        GenerationResultResponse: {
            request: components["schemas"]["GenerationRequestResponse"];
            course: components["schemas"]["CourseResponse"];
        };
        GenerationRequestResponse: {
            /** Format: uuid */
            id: string;
            initialUserPrompt: string;
            pipelineStatus: components["schemas"]["PipelineStatus"];
            currentStep: string | null;
            progressPercent: number;
            failureMessage: string | null;
            /** Format: date-time */
            startedAt: string | null;
            /** Format: date-time */
            completedAt: string | null;
            isOutOfScope: boolean;
            errorMessage: string | null;
            warningMessage: string | null;
            suggestedTitle: string | null;
            shortSynopsis: string | null;
            detectedCurrentLevel: components["schemas"]["Level"] | null;
            detectedTargetLevel: components["schemas"]["Level"] | null;
            detectedGoal: string | null;
            detectedLanguage: components["schemas"]["Language"] | null;
            clarificationQuestions: components["schemas"]["ClarificationQuestionResponse"][];
            clarificationAnswers: components["schemas"]["ClarificationAnswerResponse"][];
            confirmedBrief: components["schemas"]["GenerationBriefResponse"] | null;
            /** Format: date-time */
            analysisCompletedAt: string | null;
            /** Format: date-time */
            briefConfirmedAt: string | null;
            /** Format: date-time */
            clarificationsSubmittedAt: string | null;
            clarificationVersion: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ClarificationQuestionResponse: {
            /** @enum {string} */
            id: "goals" | "currentLevel" | "targetLevel";
            question: string;
            options: components["schemas"]["ClarificationOptionResponse"][];
            allowMultiple: boolean;
        };
        ClarificationOptionResponse: {
            value: string;
            label: string;
        };
        ClarificationAnswerResponse: {
            questionId: string;
            selectedValues: string[];
        };
        GenerationBriefResponse: {
            title: string;
            synopsis: string;
            currentLevel: components["schemas"]["Level"];
            targetLevel: components["schemas"]["Level"];
            goals: string[];
            language: components["schemas"]["Language"];
        };
        CoursePageResponse: {
            items: components["schemas"]["CourseSummaryResponse"][];
            page: number;
            pageSize: number;
            totalItems: number;
            totalPages: number;
            hasNext: boolean;
            hasPrevious: boolean;
        };
        CourseSummaryResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            requestId: string;
            language: components["schemas"]["Language"];
            status: components["schemas"]["CourseStatus"];
            title: string;
            synopsis: string;
            currentLevel: components["schemas"]["Level"];
            targetLevel: components["schemas"]["Level"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CourseResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            requestId: string;
            language: components["schemas"]["Language"];
            status: components["schemas"]["CourseStatus"];
            initialUserPrompt: string;
            title: string;
            synopsis: string;
            targetAudience: string | null;
            currentLevel: components["schemas"]["Level"];
            targetLevel: components["schemas"]["Level"];
            prerequisites: string[];
            goals: string[];
            acquiredSkills: string[];
            finalProjectTitle: string | null;
            finalProjectDescription: string | null;
            finalProjectConstraints: string[];
            /** @description Somme calculée des durées estimées des leçons. */
            totalDurationMinutes: number;
            modules: components["schemas"]["ModuleResponse"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ModuleResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            courseId: string;
            order: number;
            title: string;
            description: string;
            keyLearningPoints: string[];
            /** @description Somme calculée des durées estimées des leçons du module. */
            totalDurationMinutes: number;
            lessons: components["schemas"]["LessonResponse"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        LessonResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            moduleId: string;
            order: number;
            title: string;
            type: components["schemas"]["LessonType"];
            estimatedDurationMinutes: number;
            learningGoal: string;
            requiresDiagram: boolean;
            technicalKeywords: string[];
            contentMarkdown: string | null;
            exercises: components["schemas"]["ExerciseResponse"][];
            quizzes: components["schemas"]["QuizResponse"][];
            hasContent: boolean;
            hasStructuredActivities: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ExerciseResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            lessonId: string;
            type: components["schemas"]["ExerciseType"];
            difficulty: components["schemas"]["Difficulty"];
            title: string;
            objective: string;
            instructionsMarkdown: string;
            contentMarkdown: string;
            payload: components["schemas"]["ExercisePayloadResponse"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ExercisePayloadResponse: {
            tasks: string[];
            resources: string[];
            starterCode: string | null;
            expectedOutput: string | null;
            hints: string[];
        };
        QuizResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            lessonId: string;
            type: components["schemas"]["QuizType"];
            difficulty: components["schemas"]["Difficulty"];
            title: string;
            objective: string;
            questions: components["schemas"]["QuizQuestionResponse"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        QuizQuestionResponse: {
            order: number;
            type: components["schemas"]["QuizQuestionType"];
            question: string;
            options: components["schemas"]["QuizOptionResponse"][];
        };
        QuizOptionResponse: {
            order: number;
            text: string;
        };
        QuizAnswerResponse: {
            answer: string | null;
            answers: string[];
        };
        LessonSolutionsResponse: {
            /** Format: uuid */
            lessonId: string;
            exercises: components["schemas"]["ExerciseSolutionResponse"][];
            quizzes: components["schemas"]["QuizSolutionResponse"][];
        };
        ExerciseSolutionResponse: {
            /** Format: uuid */
            exerciseId: string;
            correctionMarkdown: string;
        };
        QuizSolutionResponse: {
            /** Format: uuid */
            quizId: string;
            questions: components["schemas"]["QuizQuestionSolutionResponse"][];
        };
        QuizQuestionSolutionResponse: {
            order: number;
            answer: components["schemas"]["QuizAnswerResponse"];
            correction: string;
        };
        /** @enum {string} */
        Language: "fr" | "en";
        /** @enum {string} */
        Level: "beginner" | "intermediate" | "advanced" | "expert" | "unknown";
        /** @enum {string} */
        LessonType: "theory" | "practice" | "mixed" | "quiz";
        /** @enum {string} */
        Difficulty: "beginner" | "intermediate" | "advanced";
        /** @enum {string} */
        ExerciseType: "guided_lab" | "coding" | "debugging" | "configuration" | "scenario" | "written_answer" | "command_line" | "mixed";
        /** @enum {string} */
        QuizType: "single_choice" | "multiple_choice" | "true_false" | "short_answer" | "mixed";
        /** @enum {string} */
        QuizQuestionType: "single_choice" | "multiple_choice" | "true_false" | "short_answer";
        /** @enum {string} */
        PipelineStatus: "queued" | "running" | "awaiting_clarification" | "completed" | "failed";
        /** @enum {string} */
        CourseStatus: "analysis_pending" | "analysis_completed" | "architecture_generating" | "structure_generated" | "lessons_generating" | "lessons_generated" | "content_generating" | "completed" | "failed";
        /** @enum {string} */
        JobStatus: "queued" | "running" | "retry_scheduled" | "completed" | "failed" | "cancelled";
        /** @enum {string} */
        JobKind: "analysis" | "architecture" | "lesson_plan" | "lesson_content" | "module_content" | "finalize_course";
    };
    responses: {
        /** @description Job durable accepté et enfilé. */
        GenerationAccepted: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "jobId": "953d5c51-337f-4e13-bf20-c5299f06ec14",
                 *       "requestId": "d8c1571f-380e-44da-be06-9de1f8ba2aff",
                 *       "status": "queued",
                 *       "jobStatus": "queued",
                 *       "statusUrl": "/api/generations/d8c1571f-380e-44da-be06-9de1f8ba2aff/status",
                 *       "jobStatusUrl": "/api/generation-jobs/953d5c51-337f-4e13-bf20-c5299f06ec14",
                 *       "resultUrl": "/api/generations/d8c1571f-380e-44da-be06-9de1f8ba2aff/result"
                 *     }
                 */
                "application/json": components["schemas"]["GenerationStartedResponse"];
            };
        };
        /** @description Corps, paramètre ou règle de validation invalide. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "validation_error",
                 *       "message": "invalid level"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Session Clerk absente ou invalide. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "unauthenticated",
                 *       "message": "authentication is required"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Ressource absente. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "course_not_found",
                 *       "message": "course not found"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description L'état courant de la ressource interdit l'opération ou la clé d'idempotence est en conflit. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "generation_not_completed",
                 *       "message": "generation is not completed"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description La demande de formation est hors du périmètre accepté. */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "generation_out_of_scope",
                 *       "message": "generation request is out of scope"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Une dépendance applicative nécessaire est indisponible. */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "service_unavailable",
                 *       "message": "generation service is unavailable"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Le body JSON dépasse la limite configurée. */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "payload_too_large",
                 *       "message": "request body is too large"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description La limite de commandes de génération est atteinte. */
        RateLimited: {
            headers: {
                /** @description Délai conseillé en secondes. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "rate_limit_exceeded",
                 *       "message": "too many generation commands"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Erreur interne masquée au client et journalisée avec sa stack trace. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "internal_error",
                 *       "message": "internal server error"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description Identifiant UUID du cours. */
        CourseID: string;
        /** @description Identifiant UUID du module. */
        ModuleID: string;
        /** @description Identifiant UUID de la leçon. */
        LessonID: string;
        /** @description Identifiant UUID de la demande de génération. */
        RequestID: string;
        /** @description Identifiant UUID du job de génération. */
        JobID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Le processus HTTP est disponible. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Le processus HTTP répond. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description L'API est prête à accepter du trafic. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description PostgreSQL est indisponible ou le worker est désactivé. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    listGenerationRequests: {
        parameters: {
            query?: {
                status?: components["schemas"]["PipelineStatus"];
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page de demandes de génération. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationPageResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    startFullGeneration: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Clé stable recommandée pour rejouer la création sans dupliquer la demande. Réutiliser une clé avec un autre prompt retourne 409.
                 * @example course-linux-2026-08-18
                 */
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "prompt": "Je veux une formation sur Linux pour administrer des serveurs."
                 *     }
                 */
                "application/json": components["schemas"]["StartGenerationRequest"];
            };
        };
        responses: {
            202: components["responses"]["GenerationAccepted"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    deleteGenerationRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant UUID de la demande de génération. */
                requestID: components["parameters"]["RequestID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Demande supprimée. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    submitGenerationClarifications: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant UUID de la demande de génération. */
                requestID: components["parameters"]["RequestID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "answers": [
                 *         {
                 *           "questionId": "currentLevel",
                 *           "selectedValues": [
                 *             "beginner"
                 *           ]
                 *         },
                 *         {
                 *           "questionId": "targetLevel",
                 *           "selectedValues": [
                 *             "advanced"
                 *           ]
                 *         },
                 *         {
                 *           "questionId": "goals",
                 *           "selectedValues": [
                 *             "server_administration"
                 *           ]
                 *         }
                 *       ],
                 *       "title": "Administration Linux de débutant à avancé",
                 *       "synopsis": "Une progression pratique couvrant le shell, le système et l'administration de serveurs.",
                 *       "language": "fr"
                 *     }
                 */
                "application/json": components["schemas"]["SubmitClarificationsRequest"];
            };
        };
        responses: {
            202: components["responses"]["GenerationAccepted"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    generateCourseStructure: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant UUID de la demande de génération. */
                requestID: components["parameters"]["RequestID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "title": "Formation Docker pour déployer une API",
                 *       "synopsis": "Une progression pratique de l'image au déploiement.",
                 *       "currentLevel": "beginner",
                 *       "targetLevel": "intermediate",
                 *       "goals": [
                 *         "Comprendre Docker",
                 *         "Conteneuriser une API"
                 *       ],
                 *       "language": "fr"
                 *     }
                 */
                "application/json": components["schemas"]["GenerateStructureRequest"];
            };
        };
        responses: {
            202: components["responses"]["GenerationAccepted"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["UnprocessableEntity"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    retryCourseStructure: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant UUID de la demande de génération. */
                requestID: components["parameters"]["RequestID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateStructureRequest"];
            };
        };
        responses: {
            202: components["responses"]["GenerationAccepted"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["UnprocessableEntity"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    generateLessonContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant UUID de la leçon. */
                lessonID: components["parameters"]["LessonID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: components["responses"]["GenerationAccepted"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    generateModuleLessonContents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant UUID du module. */
                moduleID: components["parameters"]["ModuleID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: components["responses"]["GenerationAccepted"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getGenerationStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant UUID de la demande de génération. */
                requestID: components["parameters"]["RequestID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description État courant de la pipeline. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationStatusResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getGenerationResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant UUID de la demande de génération. */
                requestID: components["parameters"]["RequestID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Formation complète générée. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationResultResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    retryFullGeneration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant UUID de la demande de génération. */
                requestID: components["parameters"]["RequestID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: components["responses"]["GenerationAccepted"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listGenerationJobs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant UUID de la demande de génération. */
                requestID: components["parameters"]["RequestID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Jobs de la demande. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationJobResponse"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getGenerationJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant UUID du job de génération. */
                jobID: components["parameters"]["JobID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description État du job. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationJobResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listCourses: {
        parameters: {
            query?: {
                /** @description Recherche textuelle insensible à la casse dans le titre ou le synopsis. */
                search?: string;
                /** @description Filtre sur l'état de génération du cours. */
                status?: components["schemas"]["CourseStatus"];
                language?: components["schemas"]["Language"];
                orderBy?: "created_at" | "updated_at" | "title" | "status";
                orderDirection?: "asc" | "desc";
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page de formations. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoursePageResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getCourse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant UUID du cours. */
                courseID: components["parameters"]["CourseID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Formation trouvée. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    deleteCourse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant UUID du cours. */
                courseID: components["parameters"]["CourseID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Formation supprimée, sans corps de réponse. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listCourseModules: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant UUID du cours. */
                courseID: components["parameters"]["CourseID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Modules ordonnés du cours. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleResponse"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getModule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant UUID du module. */
                moduleID: components["parameters"]["ModuleID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Module trouvé avec ses leçons. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listModuleLessons: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant UUID du module. */
                moduleID: components["parameters"]["ModuleID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Leçons ordonnées du module. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonResponse"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getLesson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant UUID de la leçon. */
                lessonID: components["parameters"]["LessonID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Leçon trouvée. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getLessonSolutions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant UUID de la leçon. */
                lessonID: components["parameters"]["LessonID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Solutions de la leçon. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonSolutionsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
}
