import type { components } from './schema.gen'

export type GenerationSummary = components['schemas']['GenerationSummaryResponse']
export type GenerationStatus = components['schemas']['GenerationStatusResponse']
export type GenerationStarted = components['schemas']['GenerationStartedResponse']
export type GenerationPage = components['schemas']['GenerationPageResponse']
export type PipelineStatus = components['schemas']['PipelineStatus']
export type Course = components['schemas']['CourseResponse']
export type CourseSummary = components['schemas']['CourseSummaryResponse']
export type CoursePage = components['schemas']['CoursePageResponse']
export type CourseStatus = components['schemas']['CourseStatus']
export type Module = components['schemas']['ModuleResponse']
export type Lesson = components['schemas']['LessonResponse']
export type LessonSolutions = components['schemas']['LessonSolutionsResponse']
export type Quiz = components['schemas']['QuizResponse']
export type QuizQuestion = components['schemas']['QuizQuestionResponse']
export type Exercise = components['schemas']['ExerciseResponse']
export type Language = components['schemas']['Language']
export type GenerationJob = components['schemas']['GenerationJobResponse']
export type ClarificationQuestion = components['schemas']['ClarificationQuestionResponse']
export type ClarificationAnswer = components['schemas']['ClarificationAnswerRequest']
