package domain

import "errors"

var (
	ErrBlankField                   = errors.New("required field is blank")
	ErrInvalidCollection            = errors.New("collection contains invalid values")
	ErrInvalidCourseLanguage        = errors.New("invalid course language")
	ErrInvalidCourseStatus          = errors.New("invalid course generation status")
	ErrInvalidGenerationStatus      = errors.New("invalid generation pipeline status")
	ErrInvalidLessonType            = errors.New("invalid lesson type")
	ErrInvalidExerciseType          = errors.New("invalid exercise type")
	ErrInvalidQuizType              = errors.New("invalid quiz type")
	ErrInvalidQuizQuestionType      = errors.New("invalid quiz question type")
	ErrInvalidDifficulty            = errors.New("invalid difficulty")
	ErrInvalidQuizAnswer            = errors.New("invalid quiz answer")
	ErrInvalidLevel                 = errors.New("invalid level")
	ErrInvalidOrder                 = errors.New("order must be greater than 0")
	ErrInvalidProgress              = errors.New("progress percent must be between 0 and 100")
	ErrInvalidDuration              = errors.New("duration must be greater than 0")
	ErrInvalidStatusTransition      = errors.New("invalid status transition")
	ErrDuplicateModuleOrder         = errors.New("duplicate module order")
	ErrDuplicateLessonOrder         = errors.New("duplicate lesson order")
	ErrDuplicateQuestionOrder       = errors.New("duplicate question order")
	ErrDuplicateOptionOrder         = errors.New("duplicate option order")
	ErrMissingCourseContent         = errors.New("course has missing generated content")
	ErrNewUUIDCreation              = errors.New("une erreur est survenue dans la creation de l'UUID")
	ErrInvalidClarification         = errors.New("invalid clarification question")
	ErrInvalidClarificationAnswer   = errors.New("invalid clarification answer")
	ErrClarificationAnswerMissing   = errors.New("a clarification answer is missing")
	ErrClarificationAnswerUnknown   = errors.New("clarification answer references an unknown question")
	ErrClarificationValueNotAllowed = errors.New("clarification answer value is not allowed")
	ErrGenerationBriefIncomplete    = errors.New("generation brief is incomplete")
	ErrGenerationRequestNotReady    = errors.New("generation request is not ready for this transition")
	ErrInvalidGenerationJobStatus   = errors.New("invalid generation job status")
	ErrInvalidGenerationJobKind     = errors.New("invalid generation job kind")
	ErrInvalidGenerationJobPayload  = errors.New("generation job payload must be a valid JSON object")
	ErrInvalidGenerationJobAttempts = errors.New("generation job attempts are invalid")
	ErrInvalidGenerationJobState    = errors.New("generation job state is inconsistent")
	ErrGenerationJobNotClaimed      = errors.New("generation job is not claimed")
	ErrGenerationJobSelfParent      = errors.New("generation job cannot be its own parent")
	ErrInvalidClerkUserID           = errors.New("invalid Clerk user id")
)
