package contract

import "errors"

var (
	ErrUnauthenticated                      = errors.New("authentication is required")
	ErrCourseNotFound                       = errors.New("course not found")
	ErrGenerationRequestNotFound            = errors.New("generation request not found")
	ErrLessonNotFound                       = errors.New("lesson not found")
	ErrModuleNotFound                       = errors.New("module not found")
	ErrGenerationJobNotFound                = errors.New("generation job not found")
	ErrGenerationJobUnavailable             = errors.New("no generation job is available")
	ErrGenerationJobClaimLost               = errors.New("generation job claim is no longer valid")
	ErrGenerationJobNotCancellable          = errors.New("generation job cannot be cancelled in its current state")
	ErrGenerationJobIdempotencyConflict     = errors.New("generation job idempotency key is already used by another operation")
	ErrGenerationActiveLimitExceeded        = errors.New("active generation limit exceeded")
	ErrGenerationDailyLimitExceeded         = errors.New("daily generation limit exceeded")
	ErrGenerationQueueSaturated             = errors.New("generation queue is saturated")
	ErrServiceDependency                    = errors.New("application service dependency is missing")
	ErrPromptRequired                       = errors.New("generation prompt is required")
	ErrPromptTooLong                        = errors.New("generation prompt exceeds 4000 characters")
	ErrGenerationOutOfScope                 = errors.New("generation request is out of scope")
	ErrGenerationAnalysisRequired           = errors.New("generation request must be analyzed before structure generation")
	ErrGenerationBriefRequired              = errors.New("generation request requires a confirmed brief")
	ErrGenerationAwaitingClarification      = errors.New("generation request is awaiting clarification")
	ErrGenerationNotAwaitingClarification   = errors.New("generation request is not awaiting clarification")
	ErrClarificationAlreadySubmitted        = errors.New("clarifications have already been submitted")
	ErrGenerationNotCompleted               = errors.New("generation is not completed")
	ErrGenerationNotRetryable               = errors.New("only failed generations can be retried")
	ErrGenerationStructureRetryNotAllowed   = errors.New("only failed structure generations can be retried")
	ErrGenerationStructureRetryStepMismatch = errors.New("generation failure is not related to structure generation")
)
