// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activities.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createLessonExercise = `-- name: CreateLessonExercise :one
INSERT INTO lesson_exercises (
  id,
  lesson_id,
  type,
  difficulty,
  title,
  objective,
  instructions_markdown,
  content_markdown,
  correction_markdown,
  payload,
  raw_ai_output,
  created_at,
  updated_at
)
VALUES (
  $1,
  $2,
  $3::exercise_type,
  $4::activity_difficulty,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10::jsonb,
  $11::jsonb,
  $12,
  $13
)
RETURNING
  id,
  lesson_id,
  type,
  difficulty,
  title,
  objective,
  instructions_markdown,
  content_markdown,
  correction_markdown,
  payload,
  raw_ai_output,
  created_at,
  updated_at
`

type CreateLessonExerciseParams struct {
	ID                   uuid.UUID          `db:"id" json:"id"`
	LessonID             uuid.UUID          `db:"lesson_id" json:"lesson_id"`
	Type                 ExerciseType       `db:"type" json:"type"`
	Difficulty           ActivityDifficulty `db:"difficulty" json:"difficulty"`
	Title                string             `db:"title" json:"title"`
	Objective            string             `db:"objective" json:"objective"`
	InstructionsMarkdown string             `db:"instructions_markdown" json:"instructions_markdown"`
	ContentMarkdown      string             `db:"content_markdown" json:"content_markdown"`
	CorrectionMarkdown   string             `db:"correction_markdown" json:"correction_markdown"`
	Payload              json.RawMessage    `db:"payload" json:"payload"`
	RawAiOutput          json.RawMessage    `db:"raw_ai_output" json:"raw_ai_output"`
	CreatedAt            time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt            time.Time          `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateLessonExercise(ctx context.Context, arg CreateLessonExerciseParams) (LessonExercise, error) {
	row := q.db.QueryRow(ctx, createLessonExercise,
		arg.ID,
		arg.LessonID,
		arg.Type,
		arg.Difficulty,
		arg.Title,
		arg.Objective,
		arg.InstructionsMarkdown,
		arg.ContentMarkdown,
		arg.CorrectionMarkdown,
		arg.Payload,
		arg.RawAiOutput,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i LessonExercise
	err := row.Scan(
		&i.ID,
		&i.LessonID,
		&i.Type,
		&i.Difficulty,
		&i.Title,
		&i.Objective,
		&i.InstructionsMarkdown,
		&i.ContentMarkdown,
		&i.CorrectionMarkdown,
		&i.Payload,
		&i.RawAiOutput,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

type CreateLessonExercisesParams struct {
	ID                   uuid.UUID          `db:"id" json:"id"`
	LessonID             uuid.UUID          `db:"lesson_id" json:"lesson_id"`
	Type                 ExerciseType       `db:"type" json:"type"`
	Difficulty           ActivityDifficulty `db:"difficulty" json:"difficulty"`
	Title                string             `db:"title" json:"title"`
	Objective            string             `db:"objective" json:"objective"`
	InstructionsMarkdown string             `db:"instructions_markdown" json:"instructions_markdown"`
	ContentMarkdown      string             `db:"content_markdown" json:"content_markdown"`
	CorrectionMarkdown   string             `db:"correction_markdown" json:"correction_markdown"`
	Payload              json.RawMessage    `db:"payload" json:"payload"`
	RawAiOutput          json.RawMessage    `db:"raw_ai_output" json:"raw_ai_output"`
	CreatedAt            time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt            time.Time          `db:"updated_at" json:"updated_at"`
}

const createLessonQuiz = `-- name: CreateLessonQuiz :one
INSERT INTO lesson_quizzes (
  id,
  lesson_id,
  type,
  difficulty,
  title,
  objective,
  questions,
  raw_ai_output,
  created_at,
  updated_at
)
VALUES (
  $1,
  $2,
  $3::quiz_type,
  $4::activity_difficulty,
  $5,
  $6,
  $7::jsonb,
  $8::jsonb,
  $9,
  $10
)
RETURNING
  id,
  lesson_id,
  type,
  difficulty,
  title,
  objective,
  questions,
  raw_ai_output,
  created_at,
  updated_at
`

type CreateLessonQuizParams struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	LessonID    uuid.UUID          `db:"lesson_id" json:"lesson_id"`
	Type        QuizType           `db:"type" json:"type"`
	Difficulty  ActivityDifficulty `db:"difficulty" json:"difficulty"`
	Title       string             `db:"title" json:"title"`
	Objective   string             `db:"objective" json:"objective"`
	Questions   json.RawMessage    `db:"questions" json:"questions"`
	RawAiOutput json.RawMessage    `db:"raw_ai_output" json:"raw_ai_output"`
	CreatedAt   time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time          `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateLessonQuiz(ctx context.Context, arg CreateLessonQuizParams) (LessonQuiz, error) {
	row := q.db.QueryRow(ctx, createLessonQuiz,
		arg.ID,
		arg.LessonID,
		arg.Type,
		arg.Difficulty,
		arg.Title,
		arg.Objective,
		arg.Questions,
		arg.RawAiOutput,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i LessonQuiz
	err := row.Scan(
		&i.ID,
		&i.LessonID,
		&i.Type,
		&i.Difficulty,
		&i.Title,
		&i.Objective,
		&i.Questions,
		&i.RawAiOutput,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

type CreateLessonQuizzesParams struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	LessonID    uuid.UUID          `db:"lesson_id" json:"lesson_id"`
	Type        QuizType           `db:"type" json:"type"`
	Difficulty  ActivityDifficulty `db:"difficulty" json:"difficulty"`
	Title       string             `db:"title" json:"title"`
	Objective   string             `db:"objective" json:"objective"`
	Questions   json.RawMessage    `db:"questions" json:"questions"`
	RawAiOutput json.RawMessage    `db:"raw_ai_output" json:"raw_ai_output"`
	CreatedAt   time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time          `db:"updated_at" json:"updated_at"`
}

const deleteLessonExercisesByLessonID = `-- name: DeleteLessonExercisesByLessonID :exec
DELETE FROM lesson_exercises
WHERE lesson_id = $1
`

type DeleteLessonExercisesByLessonIDParams struct {
	LessonID uuid.UUID `db:"lesson_id" json:"lesson_id"`
}

func (q *Queries) DeleteLessonExercisesByLessonID(ctx context.Context, arg DeleteLessonExercisesByLessonIDParams) error {
	_, err := q.db.Exec(ctx, deleteLessonExercisesByLessonID, arg.LessonID)
	return err
}

const deleteLessonQuizzesByLessonID = `-- name: DeleteLessonQuizzesByLessonID :exec
DELETE FROM lesson_quizzes
WHERE lesson_id = $1
`

type DeleteLessonQuizzesByLessonIDParams struct {
	LessonID uuid.UUID `db:"lesson_id" json:"lesson_id"`
}

func (q *Queries) DeleteLessonQuizzesByLessonID(ctx context.Context, arg DeleteLessonQuizzesByLessonIDParams) error {
	_, err := q.db.Exec(ctx, deleteLessonQuizzesByLessonID, arg.LessonID)
	return err
}

const listLessonExercisesByLessonID = `-- name: ListLessonExercisesByLessonID :many
SELECT
  id,
  lesson_id,
  type,
  difficulty,
  title,
  objective,
  instructions_markdown,
  content_markdown,
  correction_markdown,
  payload,
  raw_ai_output,
  created_at,
  updated_at
FROM lesson_exercises
WHERE lesson_id = $1
ORDER BY created_at ASC, id ASC
`

type ListLessonExercisesByLessonIDParams struct {
	LessonID uuid.UUID `db:"lesson_id" json:"lesson_id"`
}

func (q *Queries) ListLessonExercisesByLessonID(ctx context.Context, arg ListLessonExercisesByLessonIDParams) ([]LessonExercise, error) {
	rows, err := q.db.Query(ctx, listLessonExercisesByLessonID, arg.LessonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LessonExercise{}
	for rows.Next() {
		var i LessonExercise
		if err := rows.Scan(
			&i.ID,
			&i.LessonID,
			&i.Type,
			&i.Difficulty,
			&i.Title,
			&i.Objective,
			&i.InstructionsMarkdown,
			&i.ContentMarkdown,
			&i.CorrectionMarkdown,
			&i.Payload,
			&i.RawAiOutput,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLessonExercisesByLessonIDs = `-- name: ListLessonExercisesByLessonIDs :many
SELECT
  id,
  lesson_id,
  type,
  difficulty,
  title,
  objective,
  instructions_markdown,
  content_markdown,
  correction_markdown,
  payload,
  raw_ai_output,
  created_at,
  updated_at
FROM lesson_exercises
WHERE lesson_id = ANY($1::uuid[])
ORDER BY lesson_id ASC, created_at ASC, id ASC
`

type ListLessonExercisesByLessonIDsParams struct {
	LessonIds []uuid.UUID `db:"lesson_ids" json:"lesson_ids"`
}

func (q *Queries) ListLessonExercisesByLessonIDs(ctx context.Context, arg ListLessonExercisesByLessonIDsParams) ([]LessonExercise, error) {
	rows, err := q.db.Query(ctx, listLessonExercisesByLessonIDs, arg.LessonIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LessonExercise{}
	for rows.Next() {
		var i LessonExercise
		if err := rows.Scan(
			&i.ID,
			&i.LessonID,
			&i.Type,
			&i.Difficulty,
			&i.Title,
			&i.Objective,
			&i.InstructionsMarkdown,
			&i.ContentMarkdown,
			&i.CorrectionMarkdown,
			&i.Payload,
			&i.RawAiOutput,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLessonQuizzesByLessonID = `-- name: ListLessonQuizzesByLessonID :many
SELECT
  id,
  lesson_id,
  type,
  difficulty,
  title,
  objective,
  questions,
  raw_ai_output,
  created_at,
  updated_at
FROM lesson_quizzes
WHERE lesson_id = $1
ORDER BY created_at ASC, id ASC
`

type ListLessonQuizzesByLessonIDParams struct {
	LessonID uuid.UUID `db:"lesson_id" json:"lesson_id"`
}

func (q *Queries) ListLessonQuizzesByLessonID(ctx context.Context, arg ListLessonQuizzesByLessonIDParams) ([]LessonQuiz, error) {
	rows, err := q.db.Query(ctx, listLessonQuizzesByLessonID, arg.LessonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LessonQuiz{}
	for rows.Next() {
		var i LessonQuiz
		if err := rows.Scan(
			&i.ID,
			&i.LessonID,
			&i.Type,
			&i.Difficulty,
			&i.Title,
			&i.Objective,
			&i.Questions,
			&i.RawAiOutput,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLessonQuizzesByLessonIDs = `-- name: ListLessonQuizzesByLessonIDs :many
SELECT
  id,
  lesson_id,
  type,
  difficulty,
  title,
  objective,
  questions,
  raw_ai_output,
  created_at,
  updated_at
FROM lesson_quizzes
WHERE lesson_id = ANY($1::uuid[])
ORDER BY lesson_id ASC, created_at ASC, id ASC
`

type ListLessonQuizzesByLessonIDsParams struct {
	LessonIds []uuid.UUID `db:"lesson_ids" json:"lesson_ids"`
}

func (q *Queries) ListLessonQuizzesByLessonIDs(ctx context.Context, arg ListLessonQuizzesByLessonIDsParams) ([]LessonQuiz, error) {
	rows, err := q.db.Query(ctx, listLessonQuizzesByLessonIDs, arg.LessonIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LessonQuiz{}
	for rows.Next() {
		var i LessonQuiz
		if err := rows.Scan(
			&i.ID,
			&i.LessonID,
			&i.Type,
			&i.Difficulty,
			&i.Title,
			&i.Objective,
			&i.Questions,
			&i.RawAiOutput,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
