// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForCreateLessonExercises implements pgx.CopyFromSource.
type iteratorForCreateLessonExercises struct {
	rows                 []CreateLessonExercisesParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateLessonExercises) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateLessonExercises) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].LessonID,
		r.rows[0].Type,
		r.rows[0].Difficulty,
		r.rows[0].Title,
		r.rows[0].Objective,
		r.rows[0].InstructionsMarkdown,
		r.rows[0].ContentMarkdown,
		r.rows[0].CorrectionMarkdown,
		r.rows[0].Payload,
		r.rows[0].RawAiOutput,
		r.rows[0].CreatedAt,
		r.rows[0].UpdatedAt,
	}, nil
}

func (r iteratorForCreateLessonExercises) Err() error {
	return nil
}

func (q *Queries) CreateLessonExercises(ctx context.Context, arg []CreateLessonExercisesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"lesson_exercises"}, []string{"id", "lesson_id", "type", "difficulty", "title", "objective", "instructions_markdown", "content_markdown", "correction_markdown", "payload", "raw_ai_output", "created_at", "updated_at"}, &iteratorForCreateLessonExercises{rows: arg})
}

// iteratorForCreateLessonQuizzes implements pgx.CopyFromSource.
type iteratorForCreateLessonQuizzes struct {
	rows                 []CreateLessonQuizzesParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateLessonQuizzes) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateLessonQuizzes) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].LessonID,
		r.rows[0].Type,
		r.rows[0].Difficulty,
		r.rows[0].Title,
		r.rows[0].Objective,
		r.rows[0].Questions,
		r.rows[0].RawAiOutput,
		r.rows[0].CreatedAt,
		r.rows[0].UpdatedAt,
	}, nil
}

func (r iteratorForCreateLessonQuizzes) Err() error {
	return nil
}

func (q *Queries) CreateLessonQuizzes(ctx context.Context, arg []CreateLessonQuizzesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"lesson_quizzes"}, []string{"id", "lesson_id", "type", "difficulty", "title", "objective", "questions", "raw_ai_output", "created_at", "updated_at"}, &iteratorForCreateLessonQuizzes{rows: arg})
}

// iteratorForCreateLessons implements pgx.CopyFromSource.
type iteratorForCreateLessons struct {
	rows                 []CreateLessonsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateLessons) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateLessons) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].ModuleID,
		r.rows[0].LessonOrder,
		r.rows[0].Title,
		r.rows[0].Type,
		r.rows[0].EstimatedDurationMinutes,
		r.rows[0].LearningGoal,
		r.rows[0].RequiresDiagram,
		r.rows[0].TechnicalKeywords,
		r.rows[0].ContentMarkdown,
		r.rows[0].RawContentOutput,
		r.rows[0].CreatedAt,
		r.rows[0].UpdatedAt,
	}, nil
}

func (r iteratorForCreateLessons) Err() error {
	return nil
}

func (q *Queries) CreateLessons(ctx context.Context, arg []CreateLessonsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"lessons"}, []string{"id", "module_id", "lesson_order", "title", "type", "estimated_duration_minutes", "learning_goal", "requires_diagram", "technical_keywords", "content_markdown", "raw_content_output", "created_at", "updated_at"}, &iteratorForCreateLessons{rows: arg})
}

// iteratorForCreateModules implements pgx.CopyFromSource.
type iteratorForCreateModules struct {
	rows                 []CreateModulesParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateModules) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateModules) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].CourseID,
		r.rows[0].ModuleOrder,
		r.rows[0].Title,
		r.rows[0].Description,
		r.rows[0].KeyLearningPoints,
		r.rows[0].RawLessonsPlanOutput,
		r.rows[0].CreatedAt,
		r.rows[0].UpdatedAt,
	}, nil
}

func (r iteratorForCreateModules) Err() error {
	return nil
}

func (q *Queries) CreateModules(ctx context.Context, arg []CreateModulesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"modules"}, []string{"id", "course_id", "module_order", "title", "description", "key_learning_points", "raw_lessons_plan_output", "created_at", "updated_at"}, &iteratorForCreateModules{rows: arg})
}
