// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: courses.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const countCourses = `-- name: CountCourses :one
SELECT count(*)::bigint
FROM courses
WHERE ($1::course_generation_status IS NULL OR status = $1::course_generation_status)
  AND ($2::course_language IS NULL OR language = $2::course_language)
  AND (
    $3::text IS NULL
    OR btrim($3::text) = ''
    OR title ILIKE '%' || $3::text || '%'
    OR synopsis ILIKE '%' || $3::text || '%'
  )
`

type CountCoursesParams struct {
	Status   *CourseGenerationStatus `db:"status" json:"status"`
	Language *CourseLanguage         `db:"language" json:"language"`
	Search   *string                 `db:"search" json:"search"`
}

func (q *Queries) CountCourses(ctx context.Context, arg CountCoursesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCourses, arg.Status, arg.Language, arg.Search)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses (
  id,
  request_id,
  language,
  status,
  initial_user_prompt,
  title,
  synopsis,
  target_audience,
  current_level,
  target_level,
  prerequisites,
  goals,
  acquired_skills,
  final_project_title,
  final_project_description,
  final_project_constraints,
  raw_architecture_output,
  created_at,
  updated_at
)
VALUES (
  $1,
  $2,
  $3::course_language,
  $4::course_generation_status,
  $5,
  $6,
  $7,
  $8,
  $9::level,
  $10::level,
  $11::jsonb,
  $12::jsonb,
  $13::jsonb,
  $14,
  $15,
  $16::jsonb,
  $17::jsonb,
  $18,
  $19
)
RETURNING
  id,
  request_id,
  language,
  status,
  initial_user_prompt,
  title,
  synopsis,
  target_audience,
  current_level,
  target_level,
  prerequisites,
  goals,
  acquired_skills,
  final_project_title,
  final_project_description,
  final_project_constraints,
  generation_payload,
  raw_architecture_output,
  created_at,
  updated_at
`

type CreateCourseParams struct {
	ID                      uuid.UUID              `db:"id" json:"id"`
	RequestID               uuid.UUID              `db:"request_id" json:"request_id"`
	Language                CourseLanguage         `db:"language" json:"language"`
	Status                  CourseGenerationStatus `db:"status" json:"status"`
	InitialUserPrompt       string                 `db:"initial_user_prompt" json:"initial_user_prompt"`
	Title                   string                 `db:"title" json:"title"`
	Synopsis                string                 `db:"synopsis" json:"synopsis"`
	TargetAudience          *string                `db:"target_audience" json:"target_audience"`
	CurrentLevel            Level                  `db:"current_level" json:"current_level"`
	TargetLevel             Level                  `db:"target_level" json:"target_level"`
	Prerequisites           json.RawMessage        `db:"prerequisites" json:"prerequisites"`
	Goals                   json.RawMessage        `db:"goals" json:"goals"`
	AcquiredSkills          json.RawMessage        `db:"acquired_skills" json:"acquired_skills"`
	FinalProjectTitle       *string                `db:"final_project_title" json:"final_project_title"`
	FinalProjectDescription *string                `db:"final_project_description" json:"final_project_description"`
	FinalProjectConstraints json.RawMessage        `db:"final_project_constraints" json:"final_project_constraints"`
	RawArchitectureOutput   json.RawMessage        `db:"raw_architecture_output" json:"raw_architecture_output"`
	CreatedAt               time.Time              `db:"created_at" json:"created_at"`
	UpdatedAt               time.Time              `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, createCourse,
		arg.ID,
		arg.RequestID,
		arg.Language,
		arg.Status,
		arg.InitialUserPrompt,
		arg.Title,
		arg.Synopsis,
		arg.TargetAudience,
		arg.CurrentLevel,
		arg.TargetLevel,
		arg.Prerequisites,
		arg.Goals,
		arg.AcquiredSkills,
		arg.FinalProjectTitle,
		arg.FinalProjectDescription,
		arg.FinalProjectConstraints,
		arg.RawArchitectureOutput,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.Language,
		&i.Status,
		&i.InitialUserPrompt,
		&i.Title,
		&i.Synopsis,
		&i.TargetAudience,
		&i.CurrentLevel,
		&i.TargetLevel,
		&i.Prerequisites,
		&i.Goals,
		&i.AcquiredSkills,
		&i.FinalProjectTitle,
		&i.FinalProjectDescription,
		&i.FinalProjectConstraints,
		&i.GenerationPayload,
		&i.RawArchitectureOutput,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCourseByID = `-- name: DeleteCourseByID :execrows
DELETE FROM courses
WHERE id = $1
`

type DeleteCourseByIDParams struct {
	ID uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) DeleteCourseByID(ctx context.Context, arg DeleteCourseByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCourseByID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCourseByRequestID = `-- name: DeleteCourseByRequestID :execrows
DELETE FROM courses
WHERE request_id = $1
`

type DeleteCourseByRequestIDParams struct {
	RequestID uuid.UUID `db:"request_id" json:"request_id"`
}

func (q *Queries) DeleteCourseByRequestID(ctx context.Context, arg DeleteCourseByRequestIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCourseByRequestID, arg.RequestID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCourseByID = `-- name: GetCourseByID :one
SELECT
  id,
  request_id,
  language,
  status,
  initial_user_prompt,
  title,
  synopsis,
  target_audience,
  current_level,
  target_level,
  prerequisites,
  goals,
  acquired_skills,
  final_project_title,
  final_project_description,
  final_project_constraints,
  generation_payload,
  raw_architecture_output,
  created_at,
  updated_at
FROM courses
WHERE id = $1
`

type GetCourseByIDParams struct {
	ID uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetCourseByID(ctx context.Context, arg GetCourseByIDParams) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseByID, arg.ID)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.Language,
		&i.Status,
		&i.InitialUserPrompt,
		&i.Title,
		&i.Synopsis,
		&i.TargetAudience,
		&i.CurrentLevel,
		&i.TargetLevel,
		&i.Prerequisites,
		&i.Goals,
		&i.AcquiredSkills,
		&i.FinalProjectTitle,
		&i.FinalProjectDescription,
		&i.FinalProjectConstraints,
		&i.GenerationPayload,
		&i.RawArchitectureOutput,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCourseByRequestID = `-- name: GetCourseByRequestID :one
SELECT
  id,
  request_id,
  language,
  status,
  initial_user_prompt,
  title,
  synopsis,
  target_audience,
  current_level,
  target_level,
  prerequisites,
  goals,
  acquired_skills,
  final_project_title,
  final_project_description,
  final_project_constraints,
  generation_payload,
  raw_architecture_output,
  created_at,
  updated_at
FROM courses
WHERE request_id = $1
`

type GetCourseByRequestIDParams struct {
	RequestID uuid.UUID `db:"request_id" json:"request_id"`
}

func (q *Queries) GetCourseByRequestID(ctx context.Context, arg GetCourseByRequestIDParams) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseByRequestID, arg.RequestID)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.Language,
		&i.Status,
		&i.InitialUserPrompt,
		&i.Title,
		&i.Synopsis,
		&i.TargetAudience,
		&i.CurrentLevel,
		&i.TargetLevel,
		&i.Prerequisites,
		&i.Goals,
		&i.AcquiredSkills,
		&i.FinalProjectTitle,
		&i.FinalProjectDescription,
		&i.FinalProjectConstraints,
		&i.GenerationPayload,
		&i.RawArchitectureOutput,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isCourseContentComplete = `-- name: IsCourseContentComplete :one
SELECT
  EXISTS (
    SELECT 1
    FROM modules m
    WHERE m.course_id = $1
  )
  AND NOT EXISTS (
    SELECT 1
    FROM modules m
    WHERE m.course_id = $1
      AND NOT EXISTS (
        SELECT 1
        FROM lessons l
        WHERE l.module_id = m.id
      )
  )
  AND NOT EXISTS (
    SELECT 1
    FROM modules m
    JOIN lessons l ON l.module_id = m.id
    WHERE m.course_id = $1
      AND (l.content_markdown IS NULL OR btrim(l.content_markdown) = '')
      AND NOT EXISTS (
        SELECT 1
        FROM lesson_exercises e
        WHERE e.lesson_id = l.id
      )
      AND NOT EXISTS (
        SELECT 1
        FROM lesson_quizzes q
        WHERE q.lesson_id = l.id
      )
  ) AS is_complete
`

type IsCourseContentCompleteParams struct {
	CourseID uuid.UUID `db:"course_id" json:"course_id"`
}

func (q *Queries) IsCourseContentComplete(ctx context.Context, arg IsCourseContentCompleteParams) (*bool, error) {
	row := q.db.QueryRow(ctx, isCourseContentComplete, arg.CourseID)
	var is_complete *bool
	err := row.Scan(&is_complete)
	return is_complete, err
}

const listCoursesCreatedAtAsc = `-- name: ListCoursesCreatedAtAsc :many
SELECT
  id,
  request_id,
  language,
  status,
  initial_user_prompt,
  title,
  synopsis,
  target_audience,
  current_level,
  target_level,
  prerequisites,
  goals,
  acquired_skills,
  final_project_title,
  final_project_description,
  final_project_constraints,
  generation_payload,
  raw_architecture_output,
  created_at,
  updated_at
FROM courses
WHERE ($1::course_generation_status IS NULL OR status = $1::course_generation_status)
  AND ($2::course_language IS NULL OR language = $2::course_language)
  AND (
    $3::text IS NULL
    OR btrim($3::text) = ''
    OR title ILIKE '%' || $3::text || '%'
    OR synopsis ILIKE '%' || $3::text || '%'
  )
ORDER BY created_at ASC, id ASC
LIMIT $5 OFFSET $4
`

type ListCoursesCreatedAtAscParams struct {
	Status     *CourseGenerationStatus `db:"status" json:"status"`
	Language   *CourseLanguage         `db:"language" json:"language"`
	Search     *string                 `db:"search" json:"search"`
	OffsetRows int32                   `db:"offset_rows" json:"offset_rows"`
	LimitRows  int32                   `db:"limit_rows" json:"limit_rows"`
}

func (q *Queries) ListCoursesCreatedAtAsc(ctx context.Context, arg ListCoursesCreatedAtAscParams) ([]Course, error) {
	rows, err := q.db.Query(ctx, listCoursesCreatedAtAsc,
		arg.Status,
		arg.Language,
		arg.Search,
		arg.OffsetRows,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Course{}
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.Language,
			&i.Status,
			&i.InitialUserPrompt,
			&i.Title,
			&i.Synopsis,
			&i.TargetAudience,
			&i.CurrentLevel,
			&i.TargetLevel,
			&i.Prerequisites,
			&i.Goals,
			&i.AcquiredSkills,
			&i.FinalProjectTitle,
			&i.FinalProjectDescription,
			&i.FinalProjectConstraints,
			&i.GenerationPayload,
			&i.RawArchitectureOutput,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoursesCreatedAtDesc = `-- name: ListCoursesCreatedAtDesc :many
SELECT
  id,
  request_id,
  language,
  status,
  initial_user_prompt,
  title,
  synopsis,
  target_audience,
  current_level,
  target_level,
  prerequisites,
  goals,
  acquired_skills,
  final_project_title,
  final_project_description,
  final_project_constraints,
  generation_payload,
  raw_architecture_output,
  created_at,
  updated_at
FROM courses
WHERE ($1::course_generation_status IS NULL OR status = $1::course_generation_status)
  AND ($2::course_language IS NULL OR language = $2::course_language)
  AND (
    $3::text IS NULL
    OR btrim($3::text) = ''
    OR title ILIKE '%' || $3::text || '%'
    OR synopsis ILIKE '%' || $3::text || '%'
  )
ORDER BY created_at DESC, id DESC
LIMIT $5 OFFSET $4
`

type ListCoursesCreatedAtDescParams struct {
	Status     *CourseGenerationStatus `db:"status" json:"status"`
	Language   *CourseLanguage         `db:"language" json:"language"`
	Search     *string                 `db:"search" json:"search"`
	OffsetRows int32                   `db:"offset_rows" json:"offset_rows"`
	LimitRows  int32                   `db:"limit_rows" json:"limit_rows"`
}

func (q *Queries) ListCoursesCreatedAtDesc(ctx context.Context, arg ListCoursesCreatedAtDescParams) ([]Course, error) {
	rows, err := q.db.Query(ctx, listCoursesCreatedAtDesc,
		arg.Status,
		arg.Language,
		arg.Search,
		arg.OffsetRows,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Course{}
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.Language,
			&i.Status,
			&i.InitialUserPrompt,
			&i.Title,
			&i.Synopsis,
			&i.TargetAudience,
			&i.CurrentLevel,
			&i.TargetLevel,
			&i.Prerequisites,
			&i.Goals,
			&i.AcquiredSkills,
			&i.FinalProjectTitle,
			&i.FinalProjectDescription,
			&i.FinalProjectConstraints,
			&i.GenerationPayload,
			&i.RawArchitectureOutput,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoursesStatusAsc = `-- name: ListCoursesStatusAsc :many
SELECT
  id,
  request_id,
  language,
  status,
  initial_user_prompt,
  title,
  synopsis,
  target_audience,
  current_level,
  target_level,
  prerequisites,
  goals,
  acquired_skills,
  final_project_title,
  final_project_description,
  final_project_constraints,
  generation_payload,
  raw_architecture_output,
  created_at,
  updated_at
FROM courses
WHERE ($1::course_generation_status IS NULL OR status = $1::course_generation_status)
  AND ($2::course_language IS NULL OR language = $2::course_language)
  AND (
    $3::text IS NULL
    OR btrim($3::text) = ''
    OR title ILIKE '%' || $3::text || '%'
    OR synopsis ILIKE '%' || $3::text || '%'
  )
ORDER BY status ASC, id ASC
LIMIT $5 OFFSET $4
`

type ListCoursesStatusAscParams struct {
	Status     *CourseGenerationStatus `db:"status" json:"status"`
	Language   *CourseLanguage         `db:"language" json:"language"`
	Search     *string                 `db:"search" json:"search"`
	OffsetRows int32                   `db:"offset_rows" json:"offset_rows"`
	LimitRows  int32                   `db:"limit_rows" json:"limit_rows"`
}

func (q *Queries) ListCoursesStatusAsc(ctx context.Context, arg ListCoursesStatusAscParams) ([]Course, error) {
	rows, err := q.db.Query(ctx, listCoursesStatusAsc,
		arg.Status,
		arg.Language,
		arg.Search,
		arg.OffsetRows,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Course{}
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.Language,
			&i.Status,
			&i.InitialUserPrompt,
			&i.Title,
			&i.Synopsis,
			&i.TargetAudience,
			&i.CurrentLevel,
			&i.TargetLevel,
			&i.Prerequisites,
			&i.Goals,
			&i.AcquiredSkills,
			&i.FinalProjectTitle,
			&i.FinalProjectDescription,
			&i.FinalProjectConstraints,
			&i.GenerationPayload,
			&i.RawArchitectureOutput,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoursesStatusDesc = `-- name: ListCoursesStatusDesc :many
SELECT
  id,
  request_id,
  language,
  status,
  initial_user_prompt,
  title,
  synopsis,
  target_audience,
  current_level,
  target_level,
  prerequisites,
  goals,
  acquired_skills,
  final_project_title,
  final_project_description,
  final_project_constraints,
  generation_payload,
  raw_architecture_output,
  created_at,
  updated_at
FROM courses
WHERE ($1::course_generation_status IS NULL OR status = $1::course_generation_status)
  AND ($2::course_language IS NULL OR language = $2::course_language)
  AND (
    $3::text IS NULL
    OR btrim($3::text) = ''
    OR title ILIKE '%' || $3::text || '%'
    OR synopsis ILIKE '%' || $3::text || '%'
  )
ORDER BY status DESC, id DESC
LIMIT $5 OFFSET $4
`

type ListCoursesStatusDescParams struct {
	Status     *CourseGenerationStatus `db:"status" json:"status"`
	Language   *CourseLanguage         `db:"language" json:"language"`
	Search     *string                 `db:"search" json:"search"`
	OffsetRows int32                   `db:"offset_rows" json:"offset_rows"`
	LimitRows  int32                   `db:"limit_rows" json:"limit_rows"`
}

func (q *Queries) ListCoursesStatusDesc(ctx context.Context, arg ListCoursesStatusDescParams) ([]Course, error) {
	rows, err := q.db.Query(ctx, listCoursesStatusDesc,
		arg.Status,
		arg.Language,
		arg.Search,
		arg.OffsetRows,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Course{}
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.Language,
			&i.Status,
			&i.InitialUserPrompt,
			&i.Title,
			&i.Synopsis,
			&i.TargetAudience,
			&i.CurrentLevel,
			&i.TargetLevel,
			&i.Prerequisites,
			&i.Goals,
			&i.AcquiredSkills,
			&i.FinalProjectTitle,
			&i.FinalProjectDescription,
			&i.FinalProjectConstraints,
			&i.GenerationPayload,
			&i.RawArchitectureOutput,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoursesTitleAsc = `-- name: ListCoursesTitleAsc :many
SELECT
  id,
  request_id,
  language,
  status,
  initial_user_prompt,
  title,
  synopsis,
  target_audience,
  current_level,
  target_level,
  prerequisites,
  goals,
  acquired_skills,
  final_project_title,
  final_project_description,
  final_project_constraints,
  generation_payload,
  raw_architecture_output,
  created_at,
  updated_at
FROM courses
WHERE ($1::course_generation_status IS NULL OR status = $1::course_generation_status)
  AND ($2::course_language IS NULL OR language = $2::course_language)
  AND (
    $3::text IS NULL
    OR btrim($3::text) = ''
    OR title ILIKE '%' || $3::text || '%'
    OR synopsis ILIKE '%' || $3::text || '%'
  )
ORDER BY title ASC, id ASC
LIMIT $5 OFFSET $4
`

type ListCoursesTitleAscParams struct {
	Status     *CourseGenerationStatus `db:"status" json:"status"`
	Language   *CourseLanguage         `db:"language" json:"language"`
	Search     *string                 `db:"search" json:"search"`
	OffsetRows int32                   `db:"offset_rows" json:"offset_rows"`
	LimitRows  int32                   `db:"limit_rows" json:"limit_rows"`
}

func (q *Queries) ListCoursesTitleAsc(ctx context.Context, arg ListCoursesTitleAscParams) ([]Course, error) {
	rows, err := q.db.Query(ctx, listCoursesTitleAsc,
		arg.Status,
		arg.Language,
		arg.Search,
		arg.OffsetRows,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Course{}
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.Language,
			&i.Status,
			&i.InitialUserPrompt,
			&i.Title,
			&i.Synopsis,
			&i.TargetAudience,
			&i.CurrentLevel,
			&i.TargetLevel,
			&i.Prerequisites,
			&i.Goals,
			&i.AcquiredSkills,
			&i.FinalProjectTitle,
			&i.FinalProjectDescription,
			&i.FinalProjectConstraints,
			&i.GenerationPayload,
			&i.RawArchitectureOutput,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoursesTitleDesc = `-- name: ListCoursesTitleDesc :many
SELECT
  id,
  request_id,
  language,
  status,
  initial_user_prompt,
  title,
  synopsis,
  target_audience,
  current_level,
  target_level,
  prerequisites,
  goals,
  acquired_skills,
  final_project_title,
  final_project_description,
  final_project_constraints,
  generation_payload,
  raw_architecture_output,
  created_at,
  updated_at
FROM courses
WHERE ($1::course_generation_status IS NULL OR status = $1::course_generation_status)
  AND ($2::course_language IS NULL OR language = $2::course_language)
  AND (
    $3::text IS NULL
    OR btrim($3::text) = ''
    OR title ILIKE '%' || $3::text || '%'
    OR synopsis ILIKE '%' || $3::text || '%'
  )
ORDER BY title DESC, id DESC
LIMIT $5 OFFSET $4
`

type ListCoursesTitleDescParams struct {
	Status     *CourseGenerationStatus `db:"status" json:"status"`
	Language   *CourseLanguage         `db:"language" json:"language"`
	Search     *string                 `db:"search" json:"search"`
	OffsetRows int32                   `db:"offset_rows" json:"offset_rows"`
	LimitRows  int32                   `db:"limit_rows" json:"limit_rows"`
}

func (q *Queries) ListCoursesTitleDesc(ctx context.Context, arg ListCoursesTitleDescParams) ([]Course, error) {
	rows, err := q.db.Query(ctx, listCoursesTitleDesc,
		arg.Status,
		arg.Language,
		arg.Search,
		arg.OffsetRows,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Course{}
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.Language,
			&i.Status,
			&i.InitialUserPrompt,
			&i.Title,
			&i.Synopsis,
			&i.TargetAudience,
			&i.CurrentLevel,
			&i.TargetLevel,
			&i.Prerequisites,
			&i.Goals,
			&i.AcquiredSkills,
			&i.FinalProjectTitle,
			&i.FinalProjectDescription,
			&i.FinalProjectConstraints,
			&i.GenerationPayload,
			&i.RawArchitectureOutput,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoursesUpdatedAtAsc = `-- name: ListCoursesUpdatedAtAsc :many
SELECT
  id,
  request_id,
  language,
  status,
  initial_user_prompt,
  title,
  synopsis,
  target_audience,
  current_level,
  target_level,
  prerequisites,
  goals,
  acquired_skills,
  final_project_title,
  final_project_description,
  final_project_constraints,
  generation_payload,
  raw_architecture_output,
  created_at,
  updated_at
FROM courses
WHERE ($1::course_generation_status IS NULL OR status = $1::course_generation_status)
  AND ($2::course_language IS NULL OR language = $2::course_language)
  AND (
    $3::text IS NULL
    OR btrim($3::text) = ''
    OR title ILIKE '%' || $3::text || '%'
    OR synopsis ILIKE '%' || $3::text || '%'
  )
ORDER BY updated_at ASC, id ASC
LIMIT $5 OFFSET $4
`

type ListCoursesUpdatedAtAscParams struct {
	Status     *CourseGenerationStatus `db:"status" json:"status"`
	Language   *CourseLanguage         `db:"language" json:"language"`
	Search     *string                 `db:"search" json:"search"`
	OffsetRows int32                   `db:"offset_rows" json:"offset_rows"`
	LimitRows  int32                   `db:"limit_rows" json:"limit_rows"`
}

func (q *Queries) ListCoursesUpdatedAtAsc(ctx context.Context, arg ListCoursesUpdatedAtAscParams) ([]Course, error) {
	rows, err := q.db.Query(ctx, listCoursesUpdatedAtAsc,
		arg.Status,
		arg.Language,
		arg.Search,
		arg.OffsetRows,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Course{}
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.Language,
			&i.Status,
			&i.InitialUserPrompt,
			&i.Title,
			&i.Synopsis,
			&i.TargetAudience,
			&i.CurrentLevel,
			&i.TargetLevel,
			&i.Prerequisites,
			&i.Goals,
			&i.AcquiredSkills,
			&i.FinalProjectTitle,
			&i.FinalProjectDescription,
			&i.FinalProjectConstraints,
			&i.GenerationPayload,
			&i.RawArchitectureOutput,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoursesUpdatedAtDesc = `-- name: ListCoursesUpdatedAtDesc :many
SELECT
  id,
  request_id,
  language,
  status,
  initial_user_prompt,
  title,
  synopsis,
  target_audience,
  current_level,
  target_level,
  prerequisites,
  goals,
  acquired_skills,
  final_project_title,
  final_project_description,
  final_project_constraints,
  generation_payload,
  raw_architecture_output,
  created_at,
  updated_at
FROM courses
WHERE ($1::course_generation_status IS NULL OR status = $1::course_generation_status)
  AND ($2::course_language IS NULL OR language = $2::course_language)
  AND (
    $3::text IS NULL
    OR btrim($3::text) = ''
    OR title ILIKE '%' || $3::text || '%'
    OR synopsis ILIKE '%' || $3::text || '%'
  )
ORDER BY updated_at DESC, id DESC
LIMIT $5 OFFSET $4
`

type ListCoursesUpdatedAtDescParams struct {
	Status     *CourseGenerationStatus `db:"status" json:"status"`
	Language   *CourseLanguage         `db:"language" json:"language"`
	Search     *string                 `db:"search" json:"search"`
	OffsetRows int32                   `db:"offset_rows" json:"offset_rows"`
	LimitRows  int32                   `db:"limit_rows" json:"limit_rows"`
}

func (q *Queries) ListCoursesUpdatedAtDesc(ctx context.Context, arg ListCoursesUpdatedAtDescParams) ([]Course, error) {
	rows, err := q.db.Query(ctx, listCoursesUpdatedAtDesc,
		arg.Status,
		arg.Language,
		arg.Search,
		arg.OffsetRows,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Course{}
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.Language,
			&i.Status,
			&i.InitialUserPrompt,
			&i.Title,
			&i.Synopsis,
			&i.TargetAudience,
			&i.CurrentLevel,
			&i.TargetLevel,
			&i.Prerequisites,
			&i.Goals,
			&i.AcquiredSkills,
			&i.FinalProjectTitle,
			&i.FinalProjectDescription,
			&i.FinalProjectConstraints,
			&i.GenerationPayload,
			&i.RawArchitectureOutput,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCourse = `-- name: UpdateCourse :one
UPDATE courses
SET
  request_id = $1,
  language = $2::course_language,
  status = $3::course_generation_status,
  initial_user_prompt = $4,
  title = $5,
  synopsis = $6,
  target_audience = $7,
  current_level = $8::level,
  target_level = $9::level,
  prerequisites = $10::jsonb,
  goals = $11::jsonb,
  acquired_skills = $12::jsonb,
  final_project_title = $13,
  final_project_description = $14,
  final_project_constraints = $15::jsonb,
  raw_architecture_output = $16::jsonb,
  updated_at = $17
WHERE id = $18
RETURNING
  id,
  request_id,
  language,
  status,
  initial_user_prompt,
  title,
  synopsis,
  target_audience,
  current_level,
  target_level,
  prerequisites,
  goals,
  acquired_skills,
  final_project_title,
  final_project_description,
  final_project_constraints,
  generation_payload,
  raw_architecture_output,
  created_at,
  updated_at
`

type UpdateCourseParams struct {
	RequestID               uuid.UUID              `db:"request_id" json:"request_id"`
	Language                CourseLanguage         `db:"language" json:"language"`
	Status                  CourseGenerationStatus `db:"status" json:"status"`
	InitialUserPrompt       string                 `db:"initial_user_prompt" json:"initial_user_prompt"`
	Title                   string                 `db:"title" json:"title"`
	Synopsis                string                 `db:"synopsis" json:"synopsis"`
	TargetAudience          *string                `db:"target_audience" json:"target_audience"`
	CurrentLevel            Level                  `db:"current_level" json:"current_level"`
	TargetLevel             Level                  `db:"target_level" json:"target_level"`
	Prerequisites           json.RawMessage        `db:"prerequisites" json:"prerequisites"`
	Goals                   json.RawMessage        `db:"goals" json:"goals"`
	AcquiredSkills          json.RawMessage        `db:"acquired_skills" json:"acquired_skills"`
	FinalProjectTitle       *string                `db:"final_project_title" json:"final_project_title"`
	FinalProjectDescription *string                `db:"final_project_description" json:"final_project_description"`
	FinalProjectConstraints json.RawMessage        `db:"final_project_constraints" json:"final_project_constraints"`
	RawArchitectureOutput   json.RawMessage        `db:"raw_architecture_output" json:"raw_architecture_output"`
	UpdatedAt               time.Time              `db:"updated_at" json:"updated_at"`
	ID                      uuid.UUID              `db:"id" json:"id"`
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, updateCourse,
		arg.RequestID,
		arg.Language,
		arg.Status,
		arg.InitialUserPrompt,
		arg.Title,
		arg.Synopsis,
		arg.TargetAudience,
		arg.CurrentLevel,
		arg.TargetLevel,
		arg.Prerequisites,
		arg.Goals,
		arg.AcquiredSkills,
		arg.FinalProjectTitle,
		arg.FinalProjectDescription,
		arg.FinalProjectConstraints,
		arg.RawArchitectureOutput,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.Language,
		&i.Status,
		&i.InitialUserPrompt,
		&i.Title,
		&i.Synopsis,
		&i.TargetAudience,
		&i.CurrentLevel,
		&i.TargetLevel,
		&i.Prerequisites,
		&i.Goals,
		&i.AcquiredSkills,
		&i.FinalProjectTitle,
		&i.FinalProjectDescription,
		&i.FinalProjectConstraints,
		&i.GenerationPayload,
		&i.RawArchitectureOutput,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
