// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: generation_requests.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countGenerationRequestsByOwner = `-- name: CountGenerationRequestsByOwner :one
SELECT count(*)::bigint
FROM generation_requests AS request
WHERE request.clerk_user_id = $1
  AND (
    $2::generation_pipeline_status IS NULL
    OR request.pipeline_status = $2::generation_pipeline_status
  )
`

type CountGenerationRequestsByOwnerParams struct {
	ClerkUserID    string                    `db:"clerk_user_id" json:"clerk_user_id"`
	PipelineStatus *GenerationPipelineStatus `db:"pipeline_status" json:"pipeline_status"`
}

func (q *Queries) CountGenerationRequestsByOwner(ctx context.Context, arg CountGenerationRequestsByOwnerParams) (int64, error) {
	row := q.db.QueryRow(ctx, countGenerationRequestsByOwner, arg.ClerkUserID, arg.PipelineStatus)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createGenerationRequest = `-- name: CreateGenerationRequest :one
INSERT INTO generation_requests (
  id,
  clerk_user_id,
  initial_user_prompt,
  pipeline_status,
  current_step,
  progress_percent,
  failure_message,
  started_at,
  completed_at,
  is_out_of_scope,
  error_message,
  warning_message,
  suggested_title,
  short_synopsis,
  detected_current_level,
  detected_target_level,
  detected_goal,
  detected_language,
  clarification_questions,
  raw_analysis_output,
  analysis_completed_at,
  clarification_answers,
  confirmed_title,
  confirmed_synopsis,
  confirmed_current_level,
  confirmed_target_level,
  confirmed_goals,
  confirmed_language,
  brief_confirmed_at,
  clarifications_submitted_at,
  clarification_version,
  created_at,
  updated_at
)
VALUES (
  $1,
  $2,
  $3,
  $4::generation_pipeline_status,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  $14,
  $15::level,
  $16::level,
  $17,
  $18::course_language,
  $19::jsonb,
  $20::jsonb,
  $21,
  $22::jsonb,
  $23,
  $24,
  $25::level,
  $26::level,
  $27::jsonb,
  $28::course_language,
  $29,
  $30,
  $31,
  $32,
  $33
)
RETURNING id, initial_user_prompt, pipeline_status, current_step, progress_percent, failure_message, started_at, completed_at, is_out_of_scope, error_message, warning_message, suggested_title, short_synopsis, detected_current_level, detected_target_level, detected_goal, detected_language, clarification_questions, raw_analysis_output, created_at, updated_at, analysis_completed_at, clarification_answers, confirmed_title, confirmed_synopsis, confirmed_current_level, confirmed_target_level, confirmed_goals, confirmed_language, brief_confirmed_at, clarifications_submitted_at, clarification_version, clerk_user_id
`

type CreateGenerationRequestParams struct {
	ID                        uuid.UUID                `db:"id" json:"id"`
	ClerkUserID               string                   `db:"clerk_user_id" json:"clerk_user_id"`
	InitialUserPrompt         string                   `db:"initial_user_prompt" json:"initial_user_prompt"`
	PipelineStatus            GenerationPipelineStatus `db:"pipeline_status" json:"pipeline_status"`
	CurrentStep               *string                  `db:"current_step" json:"current_step"`
	ProgressPercent           int32                    `db:"progress_percent" json:"progress_percent"`
	FailureMessage            *string                  `db:"failure_message" json:"failure_message"`
	StartedAt                 *time.Time               `db:"started_at" json:"started_at"`
	CompletedAt               *time.Time               `db:"completed_at" json:"completed_at"`
	IsOutOfScope              bool                     `db:"is_out_of_scope" json:"is_out_of_scope"`
	ErrorMessage              *string                  `db:"error_message" json:"error_message"`
	WarningMessage            *string                  `db:"warning_message" json:"warning_message"`
	SuggestedTitle            *string                  `db:"suggested_title" json:"suggested_title"`
	ShortSynopsis             *string                  `db:"short_synopsis" json:"short_synopsis"`
	DetectedCurrentLevel      *Level                   `db:"detected_current_level" json:"detected_current_level"`
	DetectedTargetLevel       *Level                   `db:"detected_target_level" json:"detected_target_level"`
	DetectedGoal              *string                  `db:"detected_goal" json:"detected_goal"`
	DetectedLanguage          *CourseLanguage          `db:"detected_language" json:"detected_language"`
	ClarificationQuestions    json.RawMessage          `db:"clarification_questions" json:"clarification_questions"`
	RawAnalysisOutput         json.RawMessage          `db:"raw_analysis_output" json:"raw_analysis_output"`
	AnalysisCompletedAt       *time.Time               `db:"analysis_completed_at" json:"analysis_completed_at"`
	ClarificationAnswers      json.RawMessage          `db:"clarification_answers" json:"clarification_answers"`
	ConfirmedTitle            *string                  `db:"confirmed_title" json:"confirmed_title"`
	ConfirmedSynopsis         *string                  `db:"confirmed_synopsis" json:"confirmed_synopsis"`
	ConfirmedCurrentLevel     *Level                   `db:"confirmed_current_level" json:"confirmed_current_level"`
	ConfirmedTargetLevel      *Level                   `db:"confirmed_target_level" json:"confirmed_target_level"`
	ConfirmedGoals            json.RawMessage          `db:"confirmed_goals" json:"confirmed_goals"`
	ConfirmedLanguage         *CourseLanguage          `db:"confirmed_language" json:"confirmed_language"`
	BriefConfirmedAt          *time.Time               `db:"brief_confirmed_at" json:"brief_confirmed_at"`
	ClarificationsSubmittedAt *time.Time               `db:"clarifications_submitted_at" json:"clarifications_submitted_at"`
	ClarificationVersion      int32                    `db:"clarification_version" json:"clarification_version"`
	CreatedAt                 time.Time                `db:"created_at" json:"created_at"`
	UpdatedAt                 time.Time                `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateGenerationRequest(ctx context.Context, arg CreateGenerationRequestParams) (GenerationRequest, error) {
	row := q.db.QueryRow(ctx, createGenerationRequest,
		arg.ID,
		arg.ClerkUserID,
		arg.InitialUserPrompt,
		arg.PipelineStatus,
		arg.CurrentStep,
		arg.ProgressPercent,
		arg.FailureMessage,
		arg.StartedAt,
		arg.CompletedAt,
		arg.IsOutOfScope,
		arg.ErrorMessage,
		arg.WarningMessage,
		arg.SuggestedTitle,
		arg.ShortSynopsis,
		arg.DetectedCurrentLevel,
		arg.DetectedTargetLevel,
		arg.DetectedGoal,
		arg.DetectedLanguage,
		arg.ClarificationQuestions,
		arg.RawAnalysisOutput,
		arg.AnalysisCompletedAt,
		arg.ClarificationAnswers,
		arg.ConfirmedTitle,
		arg.ConfirmedSynopsis,
		arg.ConfirmedCurrentLevel,
		arg.ConfirmedTargetLevel,
		arg.ConfirmedGoals,
		arg.ConfirmedLanguage,
		arg.BriefConfirmedAt,
		arg.ClarificationsSubmittedAt,
		arg.ClarificationVersion,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i GenerationRequest
	err := row.Scan(
		&i.ID,
		&i.InitialUserPrompt,
		&i.PipelineStatus,
		&i.CurrentStep,
		&i.ProgressPercent,
		&i.FailureMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.IsOutOfScope,
		&i.ErrorMessage,
		&i.WarningMessage,
		&i.SuggestedTitle,
		&i.ShortSynopsis,
		&i.DetectedCurrentLevel,
		&i.DetectedTargetLevel,
		&i.DetectedGoal,
		&i.DetectedLanguage,
		&i.ClarificationQuestions,
		&i.RawAnalysisOutput,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AnalysisCompletedAt,
		&i.ClarificationAnswers,
		&i.ConfirmedTitle,
		&i.ConfirmedSynopsis,
		&i.ConfirmedCurrentLevel,
		&i.ConfirmedTargetLevel,
		&i.ConfirmedGoals,
		&i.ConfirmedLanguage,
		&i.BriefConfirmedAt,
		&i.ClarificationsSubmittedAt,
		&i.ClarificationVersion,
		&i.ClerkUserID,
	)
	return i, err
}

const deleteGenerationRequestByID = `-- name: DeleteGenerationRequestByID :execrows
DELETE FROM generation_requests
WHERE id = $1
`

func (q *Queries) DeleteGenerationRequestByID(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGenerationRequestByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGenerationAdmissionUsage = `-- name: GetGenerationAdmissionUsage :one
WITH admission_lock AS (
  SELECT pg_advisory_xact_lock(4931529157321281::bigint)
)
SELECT
  (
    SELECT count(*)::bigint
    FROM generation_requests AS active_request
    WHERE active_request.clerk_user_id = $1
      AND active_request.pipeline_status IN ('queued', 'running', 'awaiting_clarification')
  ) AS active_requests,
  (
    SELECT count(*)::bigint
    FROM generation_requests AS daily_request
    WHERE daily_request.clerk_user_id = $1
      AND daily_request.created_at >= $2
  ) AS daily_requests,
  (
    SELECT count(*)::bigint
    FROM generation_jobs AS pending_job
    WHERE pending_job.status IN ('queued', 'retry_scheduled', 'running')
  ) AS pending_jobs
FROM admission_lock
`

type GetGenerationAdmissionUsageParams struct {
	ClerkUserID  string    `db:"clerk_user_id" json:"clerk_user_id"`
	CreatedSince time.Time `db:"created_since" json:"created_since"`
}

type GetGenerationAdmissionUsageRow struct {
	ActiveRequests int64 `db:"active_requests" json:"active_requests"`
	DailyRequests  int64 `db:"daily_requests" json:"daily_requests"`
	PendingJobs    int64 `db:"pending_jobs" json:"pending_jobs"`
}

func (q *Queries) GetGenerationAdmissionUsage(ctx context.Context, arg GetGenerationAdmissionUsageParams) (GetGenerationAdmissionUsageRow, error) {
	row := q.db.QueryRow(ctx, getGenerationAdmissionUsage, arg.ClerkUserID, arg.CreatedSince)
	var i GetGenerationAdmissionUsageRow
	err := row.Scan(&i.ActiveRequests, &i.DailyRequests, &i.PendingJobs)
	return i, err
}

const getGenerationRequestByCourseID = `-- name: GetGenerationRequestByCourseID :one
SELECT gr.id, gr.initial_user_prompt, gr.pipeline_status, gr.current_step, gr.progress_percent, gr.failure_message, gr.started_at, gr.completed_at, gr.is_out_of_scope, gr.error_message, gr.warning_message, gr.suggested_title, gr.short_synopsis, gr.detected_current_level, gr.detected_target_level, gr.detected_goal, gr.detected_language, gr.clarification_questions, gr.raw_analysis_output, gr.created_at, gr.updated_at, gr.analysis_completed_at, gr.clarification_answers, gr.confirmed_title, gr.confirmed_synopsis, gr.confirmed_current_level, gr.confirmed_target_level, gr.confirmed_goals, gr.confirmed_language, gr.brief_confirmed_at, gr.clarifications_submitted_at, gr.clarification_version, gr.clerk_user_id
FROM generation_requests gr
JOIN courses c ON c.request_id = gr.id
WHERE c.id = $1
`

func (q *Queries) GetGenerationRequestByCourseID(ctx context.Context, courseID uuid.UUID) (GenerationRequest, error) {
	row := q.db.QueryRow(ctx, getGenerationRequestByCourseID, courseID)
	var i GenerationRequest
	err := row.Scan(
		&i.ID,
		&i.InitialUserPrompt,
		&i.PipelineStatus,
		&i.CurrentStep,
		&i.ProgressPercent,
		&i.FailureMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.IsOutOfScope,
		&i.ErrorMessage,
		&i.WarningMessage,
		&i.SuggestedTitle,
		&i.ShortSynopsis,
		&i.DetectedCurrentLevel,
		&i.DetectedTargetLevel,
		&i.DetectedGoal,
		&i.DetectedLanguage,
		&i.ClarificationQuestions,
		&i.RawAnalysisOutput,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AnalysisCompletedAt,
		&i.ClarificationAnswers,
		&i.ConfirmedTitle,
		&i.ConfirmedSynopsis,
		&i.ConfirmedCurrentLevel,
		&i.ConfirmedTargetLevel,
		&i.ConfirmedGoals,
		&i.ConfirmedLanguage,
		&i.BriefConfirmedAt,
		&i.ClarificationsSubmittedAt,
		&i.ClarificationVersion,
		&i.ClerkUserID,
	)
	return i, err
}

const getGenerationRequestByID = `-- name: GetGenerationRequestByID :one
SELECT id, initial_user_prompt, pipeline_status, current_step, progress_percent, failure_message, started_at, completed_at, is_out_of_scope, error_message, warning_message, suggested_title, short_synopsis, detected_current_level, detected_target_level, detected_goal, detected_language, clarification_questions, raw_analysis_output, created_at, updated_at, analysis_completed_at, clarification_answers, confirmed_title, confirmed_synopsis, confirmed_current_level, confirmed_target_level, confirmed_goals, confirmed_language, brief_confirmed_at, clarifications_submitted_at, clarification_version, clerk_user_id
FROM generation_requests
WHERE id = $1
`

func (q *Queries) GetGenerationRequestByID(ctx context.Context, id uuid.UUID) (GenerationRequest, error) {
	row := q.db.QueryRow(ctx, getGenerationRequestByID, id)
	var i GenerationRequest
	err := row.Scan(
		&i.ID,
		&i.InitialUserPrompt,
		&i.PipelineStatus,
		&i.CurrentStep,
		&i.ProgressPercent,
		&i.FailureMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.IsOutOfScope,
		&i.ErrorMessage,
		&i.WarningMessage,
		&i.SuggestedTitle,
		&i.ShortSynopsis,
		&i.DetectedCurrentLevel,
		&i.DetectedTargetLevel,
		&i.DetectedGoal,
		&i.DetectedLanguage,
		&i.ClarificationQuestions,
		&i.RawAnalysisOutput,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AnalysisCompletedAt,
		&i.ClarificationAnswers,
		&i.ConfirmedTitle,
		&i.ConfirmedSynopsis,
		&i.ConfirmedCurrentLevel,
		&i.ConfirmedTargetLevel,
		&i.ConfirmedGoals,
		&i.ConfirmedLanguage,
		&i.BriefConfirmedAt,
		&i.ClarificationsSubmittedAt,
		&i.ClarificationVersion,
		&i.ClerkUserID,
	)
	return i, err
}

const getGenerationRequestForUpdate = `-- name: GetGenerationRequestForUpdate :one
SELECT id, initial_user_prompt, pipeline_status, current_step, progress_percent, failure_message, started_at, completed_at, is_out_of_scope, error_message, warning_message, suggested_title, short_synopsis, detected_current_level, detected_target_level, detected_goal, detected_language, clarification_questions, raw_analysis_output, created_at, updated_at, analysis_completed_at, clarification_answers, confirmed_title, confirmed_synopsis, confirmed_current_level, confirmed_target_level, confirmed_goals, confirmed_language, brief_confirmed_at, clarifications_submitted_at, clarification_version, clerk_user_id
FROM generation_requests
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetGenerationRequestForUpdate(ctx context.Context, id uuid.UUID) (GenerationRequest, error) {
	row := q.db.QueryRow(ctx, getGenerationRequestForUpdate, id)
	var i GenerationRequest
	err := row.Scan(
		&i.ID,
		&i.InitialUserPrompt,
		&i.PipelineStatus,
		&i.CurrentStep,
		&i.ProgressPercent,
		&i.FailureMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.IsOutOfScope,
		&i.ErrorMessage,
		&i.WarningMessage,
		&i.SuggestedTitle,
		&i.ShortSynopsis,
		&i.DetectedCurrentLevel,
		&i.DetectedTargetLevel,
		&i.DetectedGoal,
		&i.DetectedLanguage,
		&i.ClarificationQuestions,
		&i.RawAnalysisOutput,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AnalysisCompletedAt,
		&i.ClarificationAnswers,
		&i.ConfirmedTitle,
		&i.ConfirmedSynopsis,
		&i.ConfirmedCurrentLevel,
		&i.ConfirmedTargetLevel,
		&i.ConfirmedGoals,
		&i.ConfirmedLanguage,
		&i.BriefConfirmedAt,
		&i.ClarificationsSubmittedAt,
		&i.ClarificationVersion,
		&i.ClerkUserID,
	)
	return i, err
}

const getGenerationStatusByID = `-- name: GetGenerationStatusByID :one
SELECT
  gr.id AS request_id,
  gr.pipeline_status,
  gr.current_step,
  gr.progress_percent,
  gr.failure_message,
  gr.is_out_of_scope,
	gr.error_message,
	gr.warning_message,
	gr.suggested_title,
	gr.short_synopsis,
	gr.detected_current_level,
	gr.detected_target_level,
	gr.detected_goal,
	gr.detected_language,
  gr.clarification_questions,
  c.id AS course_id,
  c.status AS course_status
FROM generation_requests gr
LEFT JOIN courses c ON c.request_id = gr.id
WHERE gr.id = $1
`

type GetGenerationStatusByIDRow struct {
	RequestID              uuid.UUID                `db:"request_id" json:"request_id"`
	PipelineStatus         GenerationPipelineStatus `db:"pipeline_status" json:"pipeline_status"`
	CurrentStep            *string                  `db:"current_step" json:"current_step"`
	ProgressPercent        int32                    `db:"progress_percent" json:"progress_percent"`
	FailureMessage         *string                  `db:"failure_message" json:"failure_message"`
	IsOutOfScope           bool                     `db:"is_out_of_scope" json:"is_out_of_scope"`
	ErrorMessage           *string                  `db:"error_message" json:"error_message"`
	WarningMessage         *string                  `db:"warning_message" json:"warning_message"`
	SuggestedTitle         *string                  `db:"suggested_title" json:"suggested_title"`
	ShortSynopsis          *string                  `db:"short_synopsis" json:"short_synopsis"`
	DetectedCurrentLevel   *Level                   `db:"detected_current_level" json:"detected_current_level"`
	DetectedTargetLevel    *Level                   `db:"detected_target_level" json:"detected_target_level"`
	DetectedGoal           *string                  `db:"detected_goal" json:"detected_goal"`
	DetectedLanguage       *CourseLanguage          `db:"detected_language" json:"detected_language"`
	ClarificationQuestions json.RawMessage          `db:"clarification_questions" json:"clarification_questions"`
	CourseID               pgtype.UUID              `db:"course_id" json:"course_id"`
	CourseStatus           *CourseGenerationStatus  `db:"course_status" json:"course_status"`
}

func (q *Queries) GetGenerationStatusByID(ctx context.Context, id uuid.UUID) (GetGenerationStatusByIDRow, error) {
	row := q.db.QueryRow(ctx, getGenerationStatusByID, id)
	var i GetGenerationStatusByIDRow
	err := row.Scan(
		&i.RequestID,
		&i.PipelineStatus,
		&i.CurrentStep,
		&i.ProgressPercent,
		&i.FailureMessage,
		&i.IsOutOfScope,
		&i.ErrorMessage,
		&i.WarningMessage,
		&i.SuggestedTitle,
		&i.ShortSynopsis,
		&i.DetectedCurrentLevel,
		&i.DetectedTargetLevel,
		&i.DetectedGoal,
		&i.DetectedLanguage,
		&i.ClarificationQuestions,
		&i.CourseID,
		&i.CourseStatus,
	)
	return i, err
}

const listGenerationRequestsByOwner = `-- name: ListGenerationRequestsByOwner :many
SELECT
  request.id AS request_id,
  course.id AS course_id,
  request.initial_user_prompt,
  COALESCE(course.title, request.confirmed_title, request.suggested_title, request.initial_user_prompt) AS title,
  request.pipeline_status,
  course.status AS course_status,
  request.current_step,
  request.progress_percent,
  request.is_out_of_scope,
  request.failure_message,
  request.created_at,
  request.updated_at
FROM generation_requests AS request
LEFT JOIN courses AS course ON course.request_id = request.id
WHERE request.clerk_user_id = $1
  AND (
    $2::generation_pipeline_status IS NULL
    OR request.pipeline_status = $2::generation_pipeline_status
  )
ORDER BY request.created_at DESC, request.id DESC
LIMIT $4
OFFSET $3
`

type ListGenerationRequestsByOwnerParams struct {
	ClerkUserID    string                    `db:"clerk_user_id" json:"clerk_user_id"`
	PipelineStatus *GenerationPipelineStatus `db:"pipeline_status" json:"pipeline_status"`
	OffsetRows     int32                     `db:"offset_rows" json:"offset_rows"`
	LimitRows      int32                     `db:"limit_rows" json:"limit_rows"`
}

type ListGenerationRequestsByOwnerRow struct {
	RequestID         uuid.UUID                `db:"request_id" json:"request_id"`
	CourseID          pgtype.UUID              `db:"course_id" json:"course_id"`
	InitialUserPrompt string                   `db:"initial_user_prompt" json:"initial_user_prompt"`
	Title             string                   `db:"title" json:"title"`
	PipelineStatus    GenerationPipelineStatus `db:"pipeline_status" json:"pipeline_status"`
	CourseStatus      *CourseGenerationStatus  `db:"course_status" json:"course_status"`
	CurrentStep       *string                  `db:"current_step" json:"current_step"`
	ProgressPercent   int32                    `db:"progress_percent" json:"progress_percent"`
	IsOutOfScope      bool                     `db:"is_out_of_scope" json:"is_out_of_scope"`
	FailureMessage    *string                  `db:"failure_message" json:"failure_message"`
	CreatedAt         time.Time                `db:"created_at" json:"created_at"`
	UpdatedAt         time.Time                `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListGenerationRequestsByOwner(ctx context.Context, arg ListGenerationRequestsByOwnerParams) ([]ListGenerationRequestsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listGenerationRequestsByOwner,
		arg.ClerkUserID,
		arg.PipelineStatus,
		arg.OffsetRows,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGenerationRequestsByOwnerRow{}
	for rows.Next() {
		var i ListGenerationRequestsByOwnerRow
		if err := rows.Scan(
			&i.RequestID,
			&i.CourseID,
			&i.InitialUserPrompt,
			&i.Title,
			&i.PipelineStatus,
			&i.CourseStatus,
			&i.CurrentStep,
			&i.ProgressPercent,
			&i.IsOutOfScope,
			&i.FailureMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeRawGenerationOutputsBefore = `-- name: PurgeRawGenerationOutputsBefore :one
WITH eligible_requests AS MATERIALIZED (
  SELECT retained_request.id
  FROM generation_requests AS retained_request
  WHERE retained_request.pipeline_status IN ('completed', 'failed')
    AND retained_request.updated_at < $1
    AND (
      retained_request.raw_analysis_output IS NOT NULL
      OR EXISTS (
        SELECT 1
        FROM courses AS retained_course
        WHERE retained_course.request_id = retained_request.id
          AND retained_course.raw_architecture_output IS NOT NULL
      )
      OR EXISTS (
        SELECT 1
        FROM modules AS retained_module
        JOIN courses AS retained_course ON retained_course.id = retained_module.course_id
        WHERE retained_course.request_id = retained_request.id
          AND (retained_module.raw_module_output IS NOT NULL OR retained_module.raw_lessons_plan_output IS NOT NULL)
      )
      OR EXISTS (
        SELECT 1
        FROM lessons AS retained_lesson
        JOIN modules AS retained_module ON retained_module.id = retained_lesson.module_id
        JOIN courses AS retained_course ON retained_course.id = retained_module.course_id
        WHERE retained_course.request_id = retained_request.id
          AND retained_lesson.raw_content_output IS NOT NULL
      )
      OR EXISTS (
        SELECT 1
        FROM lesson_exercises AS retained_exercise
        JOIN lessons AS retained_lesson ON retained_lesson.id = retained_exercise.lesson_id
        JOIN modules AS retained_module ON retained_module.id = retained_lesson.module_id
        JOIN courses AS retained_course ON retained_course.id = retained_module.course_id
        WHERE retained_course.request_id = retained_request.id
          AND retained_exercise.raw_ai_output IS NOT NULL
      )
      OR EXISTS (
        SELECT 1
        FROM lesson_quizzes AS retained_quiz
        JOIN lessons AS retained_lesson ON retained_lesson.id = retained_quiz.lesson_id
        JOIN modules AS retained_module ON retained_module.id = retained_lesson.module_id
        JOIN courses AS retained_course ON retained_course.id = retained_module.course_id
        WHERE retained_course.request_id = retained_request.id
          AND retained_quiz.raw_ai_output IS NOT NULL
      )
    )
  ORDER BY retained_request.updated_at ASC, retained_request.id ASC
  LIMIT $2
),
purged_requests AS (
  UPDATE generation_requests
  SET raw_analysis_output = NULL
  WHERE id IN (SELECT id FROM eligible_requests)
),
purged_courses AS (
  UPDATE courses
  SET raw_architecture_output = NULL
  WHERE request_id IN (SELECT id FROM eligible_requests)
),
purged_modules AS (
  UPDATE modules
  SET raw_module_output = NULL,
      raw_lessons_plan_output = NULL
  WHERE course_id IN (SELECT id FROM courses WHERE request_id IN (SELECT id FROM eligible_requests))
),
purged_lessons AS (
  UPDATE lessons
  SET raw_content_output = NULL
  WHERE module_id IN (
    SELECT modules.id
    FROM modules
    JOIN courses ON courses.id = modules.course_id
    WHERE courses.request_id IN (SELECT id FROM eligible_requests)
  )
),
purged_exercises AS (
  UPDATE lesson_exercises
  SET raw_ai_output = NULL
  WHERE lesson_id IN (
    SELECT lessons.id
    FROM lessons
    JOIN modules ON modules.id = lessons.module_id
    JOIN courses ON courses.id = modules.course_id
    WHERE courses.request_id IN (SELECT id FROM eligible_requests)
  )
),
purged_quizzes AS (
  UPDATE lesson_quizzes
  SET raw_ai_output = NULL
  WHERE lesson_id IN (
    SELECT lessons.id
    FROM lessons
    JOIN modules ON modules.id = lessons.module_id
    JOIN courses ON courses.id = modules.course_id
    WHERE courses.request_id IN (SELECT id FROM eligible_requests)
  )
)
SELECT count(*)::bigint AS purged_requests
FROM eligible_requests
`

type PurgeRawGenerationOutputsBeforeParams struct {
	Cutoff    time.Time `db:"cutoff" json:"cutoff"`
	LimitRows int32     `db:"limit_rows" json:"limit_rows"`
}

func (q *Queries) PurgeRawGenerationOutputsBefore(ctx context.Context, arg PurgeRawGenerationOutputsBeforeParams) (int64, error) {
	row := q.db.QueryRow(ctx, purgeRawGenerationOutputsBefore, arg.Cutoff, arg.LimitRows)
	var purged_requests int64
	err := row.Scan(&purged_requests)
	return purged_requests, err
}

const updateGenerationRequest = `-- name: UpdateGenerationRequest :one
UPDATE generation_requests
SET
  clerk_user_id = $1,
  initial_user_prompt = $2,
  pipeline_status = $3::generation_pipeline_status,
  current_step = $4,
  progress_percent = $5,
  failure_message = $6,
  started_at = $7,
  completed_at = $8,
  is_out_of_scope = $9,
  error_message = $10,
  warning_message = $11,
  suggested_title = $12,
  short_synopsis = $13,
  detected_current_level = $14::level,
  detected_target_level = $15::level,
  detected_goal = $16,
  detected_language = $17::course_language,
  clarification_questions = $18::jsonb,
  raw_analysis_output = $19::jsonb,
  analysis_completed_at = $20,
  clarification_answers = $21::jsonb,
  confirmed_title = $22,
  confirmed_synopsis = $23,
  confirmed_current_level = $24::level,
  confirmed_target_level = $25::level,
  confirmed_goals = $26::jsonb,
  confirmed_language = $27::course_language,
  brief_confirmed_at = $28,
  clarifications_submitted_at = $29,
  clarification_version = $30,
  updated_at = $31
WHERE id = $32
RETURNING id, initial_user_prompt, pipeline_status, current_step, progress_percent, failure_message, started_at, completed_at, is_out_of_scope, error_message, warning_message, suggested_title, short_synopsis, detected_current_level, detected_target_level, detected_goal, detected_language, clarification_questions, raw_analysis_output, created_at, updated_at, analysis_completed_at, clarification_answers, confirmed_title, confirmed_synopsis, confirmed_current_level, confirmed_target_level, confirmed_goals, confirmed_language, brief_confirmed_at, clarifications_submitted_at, clarification_version, clerk_user_id
`

type UpdateGenerationRequestParams struct {
	ClerkUserID               string                   `db:"clerk_user_id" json:"clerk_user_id"`
	InitialUserPrompt         string                   `db:"initial_user_prompt" json:"initial_user_prompt"`
	PipelineStatus            GenerationPipelineStatus `db:"pipeline_status" json:"pipeline_status"`
	CurrentStep               *string                  `db:"current_step" json:"current_step"`
	ProgressPercent           int32                    `db:"progress_percent" json:"progress_percent"`
	FailureMessage            *string                  `db:"failure_message" json:"failure_message"`
	StartedAt                 *time.Time               `db:"started_at" json:"started_at"`
	CompletedAt               *time.Time               `db:"completed_at" json:"completed_at"`
	IsOutOfScope              bool                     `db:"is_out_of_scope" json:"is_out_of_scope"`
	ErrorMessage              *string                  `db:"error_message" json:"error_message"`
	WarningMessage            *string                  `db:"warning_message" json:"warning_message"`
	SuggestedTitle            *string                  `db:"suggested_title" json:"suggested_title"`
	ShortSynopsis             *string                  `db:"short_synopsis" json:"short_synopsis"`
	DetectedCurrentLevel      *Level                   `db:"detected_current_level" json:"detected_current_level"`
	DetectedTargetLevel       *Level                   `db:"detected_target_level" json:"detected_target_level"`
	DetectedGoal              *string                  `db:"detected_goal" json:"detected_goal"`
	DetectedLanguage          *CourseLanguage          `db:"detected_language" json:"detected_language"`
	ClarificationQuestions    json.RawMessage          `db:"clarification_questions" json:"clarification_questions"`
	RawAnalysisOutput         json.RawMessage          `db:"raw_analysis_output" json:"raw_analysis_output"`
	AnalysisCompletedAt       *time.Time               `db:"analysis_completed_at" json:"analysis_completed_at"`
	ClarificationAnswers      json.RawMessage          `db:"clarification_answers" json:"clarification_answers"`
	ConfirmedTitle            *string                  `db:"confirmed_title" json:"confirmed_title"`
	ConfirmedSynopsis         *string                  `db:"confirmed_synopsis" json:"confirmed_synopsis"`
	ConfirmedCurrentLevel     *Level                   `db:"confirmed_current_level" json:"confirmed_current_level"`
	ConfirmedTargetLevel      *Level                   `db:"confirmed_target_level" json:"confirmed_target_level"`
	ConfirmedGoals            json.RawMessage          `db:"confirmed_goals" json:"confirmed_goals"`
	ConfirmedLanguage         *CourseLanguage          `db:"confirmed_language" json:"confirmed_language"`
	BriefConfirmedAt          *time.Time               `db:"brief_confirmed_at" json:"brief_confirmed_at"`
	ClarificationsSubmittedAt *time.Time               `db:"clarifications_submitted_at" json:"clarifications_submitted_at"`
	ClarificationVersion      int32                    `db:"clarification_version" json:"clarification_version"`
	UpdatedAt                 time.Time                `db:"updated_at" json:"updated_at"`
	ID                        uuid.UUID                `db:"id" json:"id"`
}

func (q *Queries) UpdateGenerationRequest(ctx context.Context, arg UpdateGenerationRequestParams) (GenerationRequest, error) {
	row := q.db.QueryRow(ctx, updateGenerationRequest,
		arg.ClerkUserID,
		arg.InitialUserPrompt,
		arg.PipelineStatus,
		arg.CurrentStep,
		arg.ProgressPercent,
		arg.FailureMessage,
		arg.StartedAt,
		arg.CompletedAt,
		arg.IsOutOfScope,
		arg.ErrorMessage,
		arg.WarningMessage,
		arg.SuggestedTitle,
		arg.ShortSynopsis,
		arg.DetectedCurrentLevel,
		arg.DetectedTargetLevel,
		arg.DetectedGoal,
		arg.DetectedLanguage,
		arg.ClarificationQuestions,
		arg.RawAnalysisOutput,
		arg.AnalysisCompletedAt,
		arg.ClarificationAnswers,
		arg.ConfirmedTitle,
		arg.ConfirmedSynopsis,
		arg.ConfirmedCurrentLevel,
		arg.ConfirmedTargetLevel,
		arg.ConfirmedGoals,
		arg.ConfirmedLanguage,
		arg.BriefConfirmedAt,
		arg.ClarificationsSubmittedAt,
		arg.ClarificationVersion,
		arg.UpdatedAt,
		arg.ID,
	)
	var i GenerationRequest
	err := row.Scan(
		&i.ID,
		&i.InitialUserPrompt,
		&i.PipelineStatus,
		&i.CurrentStep,
		&i.ProgressPercent,
		&i.FailureMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.IsOutOfScope,
		&i.ErrorMessage,
		&i.WarningMessage,
		&i.SuggestedTitle,
		&i.ShortSynopsis,
		&i.DetectedCurrentLevel,
		&i.DetectedTargetLevel,
		&i.DetectedGoal,
		&i.DetectedLanguage,
		&i.ClarificationQuestions,
		&i.RawAnalysisOutput,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AnalysisCompletedAt,
		&i.ClarificationAnswers,
		&i.ConfirmedTitle,
		&i.ConfirmedSynopsis,
		&i.ConfirmedCurrentLevel,
		&i.ConfirmedTargetLevel,
		&i.ConfirmedGoals,
		&i.ConfirmedLanguage,
		&i.BriefConfirmedAt,
		&i.ClarificationsSubmittedAt,
		&i.ClarificationVersion,
		&i.ClerkUserID,
	)
	return i, err
}
