// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: generation_requests.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createGenerationRequest = `-- name: CreateGenerationRequest :one
INSERT INTO generation_requests (
  id,
  initial_user_prompt,
  pipeline_status,
  current_step,
  progress_percent,
  failure_message,
  started_at,
  completed_at,
  is_out_of_scope,
  error_message,
  warning_message,
  suggested_title,
  short_synopsis,
  detected_current_level,
  detected_target_level,
  detected_goal,
  detected_language,
  clarification_questions,
  raw_analysis_output,
  created_at,
  updated_at
)
VALUES (
  $1,
  $2,
  $3::generation_pipeline_status,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  $14::level,
  $15::level,
  $16,
  $17::course_language,
  $18::jsonb,
  $19::jsonb,
  $20,
  $21
)
RETURNING
  id,
  initial_user_prompt,
  pipeline_status,
  current_step,
  progress_percent,
  failure_message,
  started_at,
  completed_at,
  is_out_of_scope,
  error_message,
  warning_message,
  suggested_title,
  short_synopsis,
  detected_current_level,
  detected_target_level,
  detected_goal,
  detected_language,
  clarification_questions,
  raw_analysis_output,
  created_at,
  updated_at
`

type CreateGenerationRequestParams struct {
	ID                     uuid.UUID                `db:"id" json:"id"`
	InitialUserPrompt      string                   `db:"initial_user_prompt" json:"initial_user_prompt"`
	PipelineStatus         GenerationPipelineStatus `db:"pipeline_status" json:"pipeline_status"`
	CurrentStep            *string                  `db:"current_step" json:"current_step"`
	ProgressPercent        int32                    `db:"progress_percent" json:"progress_percent"`
	FailureMessage         *string                  `db:"failure_message" json:"failure_message"`
	StartedAt              *time.Time               `db:"started_at" json:"started_at"`
	CompletedAt            *time.Time               `db:"completed_at" json:"completed_at"`
	IsOutOfScope           bool                     `db:"is_out_of_scope" json:"is_out_of_scope"`
	ErrorMessage           *string                  `db:"error_message" json:"error_message"`
	WarningMessage         *string                  `db:"warning_message" json:"warning_message"`
	SuggestedTitle         *string                  `db:"suggested_title" json:"suggested_title"`
	ShortSynopsis          *string                  `db:"short_synopsis" json:"short_synopsis"`
	DetectedCurrentLevel   *Level                   `db:"detected_current_level" json:"detected_current_level"`
	DetectedTargetLevel    *Level                   `db:"detected_target_level" json:"detected_target_level"`
	DetectedGoal           *string                  `db:"detected_goal" json:"detected_goal"`
	DetectedLanguage       *CourseLanguage          `db:"detected_language" json:"detected_language"`
	ClarificationQuestions json.RawMessage          `db:"clarification_questions" json:"clarification_questions"`
	RawAnalysisOutput      json.RawMessage          `db:"raw_analysis_output" json:"raw_analysis_output"`
	CreatedAt              time.Time                `db:"created_at" json:"created_at"`
	UpdatedAt              time.Time                `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateGenerationRequest(ctx context.Context, arg CreateGenerationRequestParams) (GenerationRequest, error) {
	row := q.db.QueryRow(ctx, createGenerationRequest,
		arg.ID,
		arg.InitialUserPrompt,
		arg.PipelineStatus,
		arg.CurrentStep,
		arg.ProgressPercent,
		arg.FailureMessage,
		arg.StartedAt,
		arg.CompletedAt,
		arg.IsOutOfScope,
		arg.ErrorMessage,
		arg.WarningMessage,
		arg.SuggestedTitle,
		arg.ShortSynopsis,
		arg.DetectedCurrentLevel,
		arg.DetectedTargetLevel,
		arg.DetectedGoal,
		arg.DetectedLanguage,
		arg.ClarificationQuestions,
		arg.RawAnalysisOutput,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i GenerationRequest
	err := row.Scan(
		&i.ID,
		&i.InitialUserPrompt,
		&i.PipelineStatus,
		&i.CurrentStep,
		&i.ProgressPercent,
		&i.FailureMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.IsOutOfScope,
		&i.ErrorMessage,
		&i.WarningMessage,
		&i.SuggestedTitle,
		&i.ShortSynopsis,
		&i.DetectedCurrentLevel,
		&i.DetectedTargetLevel,
		&i.DetectedGoal,
		&i.DetectedLanguage,
		&i.ClarificationQuestions,
		&i.RawAnalysisOutput,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGenerationRequestByCourseID = `-- name: GetGenerationRequestByCourseID :one
SELECT gr.id,
  gr.initial_user_prompt,
  gr.pipeline_status,
  gr.current_step,
  gr.progress_percent,
  gr.failure_message,
  gr.started_at,
  gr.completed_at,
  gr.is_out_of_scope,
  gr.error_message,
  gr.warning_message,
  gr.suggested_title,
  gr.short_synopsis,
  gr.detected_current_level,
  gr.detected_target_level,
  gr.detected_goal,
  gr.detected_language,
  gr.clarification_questions,
  gr.raw_analysis_output,
  gr.created_at,
  gr.updated_at
FROM generation_requests gr
JOIN courses c ON c.request_id = gr.id
WHERE c.id = $1
`

func (q *Queries) GetGenerationRequestByCourseID(ctx context.Context, courseID uuid.UUID) (GenerationRequest, error) {
	row := q.db.QueryRow(ctx, getGenerationRequestByCourseID, courseID)
	var i GenerationRequest
	err := row.Scan(
		&i.ID,
		&i.InitialUserPrompt,
		&i.PipelineStatus,
		&i.CurrentStep,
		&i.ProgressPercent,
		&i.FailureMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.IsOutOfScope,
		&i.ErrorMessage,
		&i.WarningMessage,
		&i.SuggestedTitle,
		&i.ShortSynopsis,
		&i.DetectedCurrentLevel,
		&i.DetectedTargetLevel,
		&i.DetectedGoal,
		&i.DetectedLanguage,
		&i.ClarificationQuestions,
		&i.RawAnalysisOutput,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGenerationRequestByID = `-- name: GetGenerationRequestByID :one
SELECT
  id,
  initial_user_prompt,
  pipeline_status,
  current_step,
  progress_percent,
  failure_message,
  started_at,
  completed_at,
  is_out_of_scope,
  error_message,
  warning_message,
  suggested_title,
  short_synopsis,
  detected_current_level,
  detected_target_level,
  detected_goal,
  detected_language,
  clarification_questions,
  raw_analysis_output,
  created_at,
  updated_at
FROM generation_requests
WHERE id = $1
`

func (q *Queries) GetGenerationRequestByID(ctx context.Context, id uuid.UUID) (GenerationRequest, error) {
	row := q.db.QueryRow(ctx, getGenerationRequestByID, id)
	var i GenerationRequest
	err := row.Scan(
		&i.ID,
		&i.InitialUserPrompt,
		&i.PipelineStatus,
		&i.CurrentStep,
		&i.ProgressPercent,
		&i.FailureMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.IsOutOfScope,
		&i.ErrorMessage,
		&i.WarningMessage,
		&i.SuggestedTitle,
		&i.ShortSynopsis,
		&i.DetectedCurrentLevel,
		&i.DetectedTargetLevel,
		&i.DetectedGoal,
		&i.DetectedLanguage,
		&i.ClarificationQuestions,
		&i.RawAnalysisOutput,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGenerationStatusByID = `-- name: GetGenerationStatusByID :one
SELECT
  gr.id AS request_id,
  gr.pipeline_status,
  gr.current_step,
  gr.progress_percent,
  gr.failure_message,
  c.id AS course_id,
  c.status AS course_status
FROM generation_requests gr
LEFT JOIN courses c ON c.request_id = gr.id
WHERE gr.id = $1
`

type GetGenerationStatusByIDRow struct {
	RequestID       uuid.UUID                `db:"request_id" json:"request_id"`
	PipelineStatus  GenerationPipelineStatus `db:"pipeline_status" json:"pipeline_status"`
	CurrentStep     *string                  `db:"current_step" json:"current_step"`
	ProgressPercent int32                    `db:"progress_percent" json:"progress_percent"`
	FailureMessage  *string                  `db:"failure_message" json:"failure_message"`
	CourseID        pgtype.UUID              `db:"course_id" json:"course_id"`
	CourseStatus    *CourseGenerationStatus  `db:"course_status" json:"course_status"`
}

func (q *Queries) GetGenerationStatusByID(ctx context.Context, id uuid.UUID) (GetGenerationStatusByIDRow, error) {
	row := q.db.QueryRow(ctx, getGenerationStatusByID, id)
	var i GetGenerationStatusByIDRow
	err := row.Scan(
		&i.RequestID,
		&i.PipelineStatus,
		&i.CurrentStep,
		&i.ProgressPercent,
		&i.FailureMessage,
		&i.CourseID,
		&i.CourseStatus,
	)
	return i, err
}

const updateGenerationRequest = `-- name: UpdateGenerationRequest :one
UPDATE generation_requests
SET
  initial_user_prompt = $1,
  pipeline_status = $2::generation_pipeline_status,
  current_step = $3,
  progress_percent = $4,
  failure_message = $5,
  started_at = $6,
  completed_at = $7,
  is_out_of_scope = $8,
  error_message = $9,
  warning_message = $10,
  suggested_title = $11,
  short_synopsis = $12,
  detected_current_level = $13::level,
  detected_target_level = $14::level,
  detected_goal = $15,
  detected_language = $16::course_language,
  clarification_questions = $17::jsonb,
  raw_analysis_output = $18::jsonb,
  updated_at = $19
WHERE id = $20
RETURNING
  id,
  initial_user_prompt,
  pipeline_status,
  current_step,
  progress_percent,
  failure_message,
  started_at,
  completed_at,
  is_out_of_scope,
  error_message,
  warning_message,
  suggested_title,
  short_synopsis,
  detected_current_level,
  detected_target_level,
  detected_goal,
  detected_language,
  clarification_questions,
  raw_analysis_output,
  created_at,
  updated_at
`

type UpdateGenerationRequestParams struct {
	InitialUserPrompt      string                   `db:"initial_user_prompt" json:"initial_user_prompt"`
	PipelineStatus         GenerationPipelineStatus `db:"pipeline_status" json:"pipeline_status"`
	CurrentStep            *string                  `db:"current_step" json:"current_step"`
	ProgressPercent        int32                    `db:"progress_percent" json:"progress_percent"`
	FailureMessage         *string                  `db:"failure_message" json:"failure_message"`
	StartedAt              *time.Time               `db:"started_at" json:"started_at"`
	CompletedAt            *time.Time               `db:"completed_at" json:"completed_at"`
	IsOutOfScope           bool                     `db:"is_out_of_scope" json:"is_out_of_scope"`
	ErrorMessage           *string                  `db:"error_message" json:"error_message"`
	WarningMessage         *string                  `db:"warning_message" json:"warning_message"`
	SuggestedTitle         *string                  `db:"suggested_title" json:"suggested_title"`
	ShortSynopsis          *string                  `db:"short_synopsis" json:"short_synopsis"`
	DetectedCurrentLevel   *Level                   `db:"detected_current_level" json:"detected_current_level"`
	DetectedTargetLevel    *Level                   `db:"detected_target_level" json:"detected_target_level"`
	DetectedGoal           *string                  `db:"detected_goal" json:"detected_goal"`
	DetectedLanguage       *CourseLanguage          `db:"detected_language" json:"detected_language"`
	ClarificationQuestions json.RawMessage          `db:"clarification_questions" json:"clarification_questions"`
	RawAnalysisOutput      json.RawMessage          `db:"raw_analysis_output" json:"raw_analysis_output"`
	UpdatedAt              time.Time                `db:"updated_at" json:"updated_at"`
	ID                     uuid.UUID                `db:"id" json:"id"`
}

func (q *Queries) UpdateGenerationRequest(ctx context.Context, arg UpdateGenerationRequestParams) (GenerationRequest, error) {
	row := q.db.QueryRow(ctx, updateGenerationRequest,
		arg.InitialUserPrompt,
		arg.PipelineStatus,
		arg.CurrentStep,
		arg.ProgressPercent,
		arg.FailureMessage,
		arg.StartedAt,
		arg.CompletedAt,
		arg.IsOutOfScope,
		arg.ErrorMessage,
		arg.WarningMessage,
		arg.SuggestedTitle,
		arg.ShortSynopsis,
		arg.DetectedCurrentLevel,
		arg.DetectedTargetLevel,
		arg.DetectedGoal,
		arg.DetectedLanguage,
		arg.ClarificationQuestions,
		arg.RawAnalysisOutput,
		arg.UpdatedAt,
		arg.ID,
	)
	var i GenerationRequest
	err := row.Scan(
		&i.ID,
		&i.InitialUserPrompt,
		&i.PipelineStatus,
		&i.CurrentStep,
		&i.ProgressPercent,
		&i.FailureMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.IsOutOfScope,
		&i.ErrorMessage,
		&i.WarningMessage,
		&i.SuggestedTitle,
		&i.ShortSynopsis,
		&i.DetectedCurrentLevel,
		&i.DetectedTargetLevel,
		&i.DetectedGoal,
		&i.DetectedLanguage,
		&i.ClarificationQuestions,
		&i.RawAnalysisOutput,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
