// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: generation_jobs.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelGenerationJob = `-- name: CancelGenerationJob :execrows
WITH request_lock AS MATERIALIZED (
 SELECT r.id FROM generation_requests r JOIN generation_jobs j ON j.request_id = r.id WHERE j.id = $2 FOR UPDATE OF r
)
UPDATE generation_jobs AS job
SET
  status = 'cancelled',
  completed_at = $1,
  updated_at = $1
WHERE job.id = $2 AND job.request_id IN (SELECT id FROM request_lock)
  AND job.status IN ('queued', 'retry_scheduled')
`

type CancelGenerationJobParams struct {
	CancelledAt *time.Time `db:"cancelled_at" json:"cancelled_at"`
	ID          uuid.UUID  `db:"id" json:"id"`
}

func (q *Queries) CancelGenerationJob(ctx context.Context, arg CancelGenerationJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelGenerationJob, arg.CancelledAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimNextGenerationJob = `-- name: ClaimNextGenerationJob :one
WITH request_lock AS MATERIALIZED (
  SELECT r.id FROM generation_requests r JOIN LATERAL (
    SELECT j.priority, j.available_at, j.created_at, j.id FROM generation_jobs j
    WHERE j.request_id = r.id AND j.generation_attempt = r.generation_attempt AND j.is_current
      AND j.status IN ('queued', 'retry_scheduled') AND j.available_at <= CURRENT_TIMESTAMP AND j.attempt_count < j.max_attempts
    ORDER BY j.priority DESC, j.available_at, j.created_at, j.id LIMIT 1
  ) next_job ON true
  ORDER BY next_job.priority DESC, next_job.available_at, next_job.created_at, next_job.id
  FOR UPDATE OF r SKIP LOCKED LIMIT 1
), candidate AS (
  SELECT id
  FROM generation_jobs
  WHERE request_id IN (SELECT id FROM request_lock) AND is_current AND status IN ('queued', 'retry_scheduled')
    AND available_at <= CURRENT_TIMESTAMP
    AND attempt_count < max_attempts
  ORDER BY priority DESC, available_at ASC, created_at ASC, id ASC
  FOR UPDATE SKIP LOCKED
  LIMIT 1
)
UPDATE generation_jobs AS job
SET
  status = 'running',
  attempt_count = job.attempt_count + 1,
  locked_by = $1,
  locked_until = $2,
  started_at = COALESCE(job.started_at, CURRENT_TIMESTAMP),
  updated_at = CURRENT_TIMESTAMP,
  last_error_code = NULL,
  last_error_message = NULL
FROM candidate
WHERE job.id = candidate.id
  AND $2 > CURRENT_TIMESTAMP
RETURNING job.id, job.request_id, job.parent_job_id, job.kind, job.status, job.target_id, job.idempotency_key, job.payload, job.priority, job.attempt_count, job.max_attempts, job.available_at, job.locked_by, job.locked_until, job.started_at, job.completed_at, job.last_error_code, job.last_error_message, job.created_at, job.updated_at, job.failure_handled_at, job.generation_attempt, job.is_current, job.operation_version, job.supersedes_job_id
`

type ClaimNextGenerationJobParams struct {
	WorkerID    *string    `db:"worker_id" json:"worker_id"`
	LockedUntil *time.Time `db:"locked_until" json:"locked_until"`
}

func (q *Queries) ClaimNextGenerationJob(ctx context.Context, arg ClaimNextGenerationJobParams) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, claimNextGenerationJob, arg.WorkerID, arg.LockedUntil)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ParentJobID,
		&i.Kind,
		&i.Status,
		&i.TargetID,
		&i.IdempotencyKey,
		&i.Payload,
		&i.Priority,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.AvailableAt,
		&i.LockedBy,
		&i.LockedUntil,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailureHandledAt,
		&i.GenerationAttempt,
		&i.IsCurrent,
		&i.OperationVersion,
		&i.SupersedesJobID,
	)
	return i, err
}

const completeGenerationJob = `-- name: CompleteGenerationJob :execrows
WITH request_lock AS MATERIALIZED (
 SELECT r.id FROM generation_requests r JOIN generation_jobs j ON j.request_id = r.id WHERE j.id = $2 FOR UPDATE OF r
)
UPDATE generation_jobs AS job
SET
  status = 'completed',
  locked_by = NULL,
  locked_until = NULL,
  completed_at = $1,
  last_error_code = NULL,
  last_error_message = NULL,
  updated_at = $1
WHERE job.id = $2 AND job.request_id IN (SELECT id FROM request_lock)
  AND job.status = 'running'
  AND job.locked_by = $3
  AND job.attempt_count = $4
  AND job.locked_until > CURRENT_TIMESTAMP
`

type CompleteGenerationJobParams struct {
	CompletedAt  *time.Time `db:"completed_at" json:"completed_at"`
	ID           uuid.UUID  `db:"id" json:"id"`
	WorkerID     *string    `db:"worker_id" json:"worker_id"`
	AttemptCount int32      `db:"attempt_count" json:"attempt_count"`
}

func (q *Queries) CompleteGenerationJob(ctx context.Context, arg CompleteGenerationJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeGenerationJob,
		arg.CompletedAt,
		arg.ID,
		arg.WorkerID,
		arg.AttemptCount,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countPendingGenerationJobsWithAdmissionLock = `-- name: CountPendingGenerationJobsWithAdmissionLock :one
WITH admission_lock AS (
  SELECT pg_advisory_xact_lock(4931529157321281::bigint)
)
SELECT count(*)::bigint
FROM generation_jobs, admission_lock
WHERE status IN ('queued', 'retry_scheduled', 'running')
`

func (q *Queries) CountPendingGenerationJobsWithAdmissionLock(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingGenerationJobsWithAdmissionLock)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const enqueueGenerationJob = `-- name: EnqueueGenerationJob :one
INSERT INTO generation_jobs (
  is_current, operation_version, supersedes_job_id,
  generation_attempt,
  id,
  request_id,
  parent_job_id,
  kind,
  status,
  target_id,
  idempotency_key,
  payload,
  priority,
  attempt_count,
  max_attempts,
  available_at,
  locked_by,
  locked_until,
  started_at,
  completed_at,
  last_error_code,
  last_error_message,
  failure_handled_at,
  created_at,
  updated_at
)
VALUES (
  $1, $2, $3,
  $4,
  $5,
  $6,
  $7,
  $8::generation_job_kind,
  $9::generation_job_status,
  $10,
  $11,
  $12::jsonb,
  $13,
  $14,
  $15,
  $16,
  $17,
  $18,
  $19,
  $20,
  $21,
  $22,
  $23,
  $24,
  $25
)
ON CONFLICT DO NOTHING
RETURNING id, request_id, parent_job_id, kind, status, target_id, idempotency_key, payload, priority, attempt_count, max_attempts, available_at, locked_by, locked_until, started_at, completed_at, last_error_code, last_error_message, created_at, updated_at, failure_handled_at, generation_attempt, is_current, operation_version, supersedes_job_id
`

type EnqueueGenerationJobParams struct {
	IsCurrent         bool                `db:"is_current" json:"is_current"`
	OperationVersion  int32               `db:"operation_version" json:"operation_version"`
	SupersedesJobID   pgtype.UUID         `db:"supersedes_job_id" json:"supersedes_job_id"`
	GenerationAttempt int32               `db:"generation_attempt" json:"generation_attempt"`
	ID                uuid.UUID           `db:"id" json:"id"`
	RequestID         uuid.UUID           `db:"request_id" json:"request_id"`
	ParentJobID       pgtype.UUID         `db:"parent_job_id" json:"parent_job_id"`
	Kind              GenerationJobKind   `db:"kind" json:"kind"`
	Status            GenerationJobStatus `db:"status" json:"status"`
	TargetID          pgtype.UUID         `db:"target_id" json:"target_id"`
	IdempotencyKey    string              `db:"idempotency_key" json:"idempotency_key"`
	Payload           json.RawMessage     `db:"payload" json:"payload"`
	Priority          int32               `db:"priority" json:"priority"`
	AttemptCount      int32               `db:"attempt_count" json:"attempt_count"`
	MaxAttempts       int32               `db:"max_attempts" json:"max_attempts"`
	AvailableAt       time.Time           `db:"available_at" json:"available_at"`
	LockedBy          *string             `db:"locked_by" json:"locked_by"`
	LockedUntil       *time.Time          `db:"locked_until" json:"locked_until"`
	StartedAt         *time.Time          `db:"started_at" json:"started_at"`
	CompletedAt       *time.Time          `db:"completed_at" json:"completed_at"`
	LastErrorCode     *string             `db:"last_error_code" json:"last_error_code"`
	LastErrorMessage  *string             `db:"last_error_message" json:"last_error_message"`
	FailureHandledAt  *time.Time          `db:"failure_handled_at" json:"failure_handled_at"`
	CreatedAt         time.Time           `db:"created_at" json:"created_at"`
	UpdatedAt         time.Time           `db:"updated_at" json:"updated_at"`
}

func (q *Queries) EnqueueGenerationJob(ctx context.Context, arg EnqueueGenerationJobParams) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, enqueueGenerationJob,
		arg.IsCurrent,
		arg.OperationVersion,
		arg.SupersedesJobID,
		arg.GenerationAttempt,
		arg.ID,
		arg.RequestID,
		arg.ParentJobID,
		arg.Kind,
		arg.Status,
		arg.TargetID,
		arg.IdempotencyKey,
		arg.Payload,
		arg.Priority,
		arg.AttemptCount,
		arg.MaxAttempts,
		arg.AvailableAt,
		arg.LockedBy,
		arg.LockedUntil,
		arg.StartedAt,
		arg.CompletedAt,
		arg.LastErrorCode,
		arg.LastErrorMessage,
		arg.FailureHandledAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ParentJobID,
		&i.Kind,
		&i.Status,
		&i.TargetID,
		&i.IdempotencyKey,
		&i.Payload,
		&i.Priority,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.AvailableAt,
		&i.LockedBy,
		&i.LockedUntil,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailureHandledAt,
		&i.GenerationAttempt,
		&i.IsCurrent,
		&i.OperationVersion,
		&i.SupersedesJobID,
	)
	return i, err
}

const failGenerationJob = `-- name: FailGenerationJob :execrows
WITH request_lock AS MATERIALIZED (
 SELECT r.id FROM generation_requests r JOIN generation_jobs j ON j.request_id = r.id WHERE j.id = $4 FOR UPDATE OF r
)
UPDATE generation_jobs AS job
SET
  status = 'failed',
  locked_by = NULL,
  locked_until = NULL,
  completed_at = $1,
  last_error_code = $2,
  last_error_message = $3,
  updated_at = $1
WHERE job.id = $4 AND job.request_id IN (SELECT id FROM request_lock)
  AND job.status = 'running'
  AND job.locked_by = $5
  AND job.attempt_count = $6
  AND job.locked_until > CURRENT_TIMESTAMP
`

type FailGenerationJobParams struct {
	FailedAt     *time.Time `db:"failed_at" json:"failed_at"`
	ErrorCode    *string    `db:"error_code" json:"error_code"`
	ErrorMessage *string    `db:"error_message" json:"error_message"`
	ID           uuid.UUID  `db:"id" json:"id"`
	WorkerID     *string    `db:"worker_id" json:"worker_id"`
	AttemptCount int32      `db:"attempt_count" json:"attempt_count"`
}

func (q *Queries) FailGenerationJob(ctx context.Context, arg FailGenerationJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, failGenerationJob,
		arg.FailedAt,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.ID,
		arg.WorkerID,
		arg.AttemptCount,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGenerationJobByID = `-- name: GetGenerationJobByID :one
SELECT id, request_id, parent_job_id, kind, status, target_id, idempotency_key, payload, priority, attempt_count, max_attempts, available_at, locked_by, locked_until, started_at, completed_at, last_error_code, last_error_message, created_at, updated_at, failure_handled_at, generation_attempt, is_current, operation_version, supersedes_job_id
FROM generation_jobs
WHERE id = $1
`

func (q *Queries) GetGenerationJobByID(ctx context.Context, id uuid.UUID) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, getGenerationJobByID, id)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ParentJobID,
		&i.Kind,
		&i.Status,
		&i.TargetID,
		&i.IdempotencyKey,
		&i.Payload,
		&i.Priority,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.AvailableAt,
		&i.LockedBy,
		&i.LockedUntil,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailureHandledAt,
		&i.GenerationAttempt,
		&i.IsCurrent,
		&i.OperationVersion,
		&i.SupersedesJobID,
	)
	return i, err
}

const getGenerationJobByIdempotencyKey = `-- name: GetGenerationJobByIdempotencyKey :one
SELECT id, request_id, parent_job_id, kind, status, target_id, idempotency_key, payload, priority, attempt_count, max_attempts, available_at, locked_by, locked_until, started_at, completed_at, last_error_code, last_error_message, created_at, updated_at, failure_handled_at, generation_attempt, is_current, operation_version, supersedes_job_id
FROM generation_jobs
WHERE idempotency_key = $1
`

func (q *Queries) GetGenerationJobByIdempotencyKey(ctx context.Context, idempotencyKey string) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, getGenerationJobByIdempotencyKey, idempotencyKey)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ParentJobID,
		&i.Kind,
		&i.Status,
		&i.TargetID,
		&i.IdempotencyKey,
		&i.Payload,
		&i.Priority,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.AvailableAt,
		&i.LockedBy,
		&i.LockedUntil,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailureHandledAt,
		&i.GenerationAttempt,
		&i.IsCurrent,
		&i.OperationVersion,
		&i.SupersedesJobID,
	)
	return i, err
}

const getGenerationQueueMetrics = `-- name: GetGenerationQueueMetrics :one
SELECT
  count(*) FILTER (WHERE status = 'queued')::bigint AS queued,
  count(*) FILTER (WHERE status = 'retry_scheduled')::bigint AS retry_scheduled,
  count(*) FILTER (WHERE status = 'running')::bigint AS running,
  count(*) FILTER (WHERE status = 'completed')::bigint AS completed,
  count(*) FILTER (WHERE status = 'failed')::bigint AS failed,
  count(*) FILTER (WHERE status = 'cancelled')::bigint AS cancelled,
  count(*) FILTER (WHERE status = 'running' AND locked_until <= CURRENT_TIMESTAMP)::bigint AS expired_leases,
  count(*) FILTER (WHERE status = 'failed' AND failure_handled_at IS NULL)::bigint AS unreconciled_failures
FROM generation_jobs
`

type GetGenerationQueueMetricsRow struct {
	Queued               int64 `db:"queued" json:"queued"`
	RetryScheduled       int64 `db:"retry_scheduled" json:"retry_scheduled"`
	Running              int64 `db:"running" json:"running"`
	Completed            int64 `db:"completed" json:"completed"`
	Failed               int64 `db:"failed" json:"failed"`
	Cancelled            int64 `db:"cancelled" json:"cancelled"`
	ExpiredLeases        int64 `db:"expired_leases" json:"expired_leases"`
	UnreconciledFailures int64 `db:"unreconciled_failures" json:"unreconciled_failures"`
}

func (q *Queries) GetGenerationQueueMetrics(ctx context.Context) (GetGenerationQueueMetricsRow, error) {
	row := q.db.QueryRow(ctx, getGenerationQueueMetrics)
	var i GetGenerationQueueMetricsRow
	err := row.Scan(
		&i.Queued,
		&i.RetryScheduled,
		&i.Running,
		&i.Completed,
		&i.Failed,
		&i.Cancelled,
		&i.ExpiredLeases,
		&i.UnreconciledFailures,
	)
	return i, err
}

const listGenerationJobsByRequestID = `-- name: ListGenerationJobsByRequestID :many
SELECT id, request_id, parent_job_id, kind, status, target_id, idempotency_key, payload, priority, attempt_count, max_attempts, available_at, locked_by, locked_until, started_at, completed_at, last_error_code, last_error_message, created_at, updated_at, failure_handled_at, generation_attempt, is_current, operation_version, supersedes_job_id
FROM generation_jobs
WHERE request_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListGenerationJobsByRequestID(ctx context.Context, requestID uuid.UUID) ([]GenerationJob, error) {
	rows, err := q.db.Query(ctx, listGenerationJobsByRequestID, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GenerationJob{}
	for rows.Next() {
		var i GenerationJob
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.ParentJobID,
			&i.Kind,
			&i.Status,
			&i.TargetID,
			&i.IdempotencyKey,
			&i.Payload,
			&i.Priority,
			&i.AttemptCount,
			&i.MaxAttempts,
			&i.AvailableAt,
			&i.LockedBy,
			&i.LockedUntil,
			&i.StartedAt,
			&i.CompletedAt,
			&i.LastErrorCode,
			&i.LastErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FailureHandledAt,
			&i.GenerationAttempt,
			&i.IsCurrent,
			&i.OperationVersion,
			&i.SupersedesJobID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreconciledFailedGenerationJobs = `-- name: ListUnreconciledFailedGenerationJobs :many
SELECT id, request_id, parent_job_id, kind, status, target_id, idempotency_key, payload, priority, attempt_count, max_attempts, available_at, locked_by, locked_until, started_at, completed_at, last_error_code, last_error_message, created_at, updated_at, failure_handled_at, generation_attempt, is_current, operation_version, supersedes_job_id
FROM generation_jobs
WHERE status = 'failed'
  AND failure_handled_at IS NULL
ORDER BY completed_at ASC, id ASC
LIMIT $1
`

func (q *Queries) ListUnreconciledFailedGenerationJobs(ctx context.Context, limitRows int32) ([]GenerationJob, error) {
	rows, err := q.db.Query(ctx, listUnreconciledFailedGenerationJobs, limitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GenerationJob{}
	for rows.Next() {
		var i GenerationJob
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.ParentJobID,
			&i.Kind,
			&i.Status,
			&i.TargetID,
			&i.IdempotencyKey,
			&i.Payload,
			&i.Priority,
			&i.AttemptCount,
			&i.MaxAttempts,
			&i.AvailableAt,
			&i.LockedBy,
			&i.LockedUntil,
			&i.StartedAt,
			&i.CompletedAt,
			&i.LastErrorCode,
			&i.LastErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FailureHandledAt,
			&i.GenerationAttempt,
			&i.IsCurrent,
			&i.OperationVersion,
			&i.SupersedesJobID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockGenerationJobClaim = `-- name: LockGenerationJobClaim :one
SELECT id FROM generation_jobs
WHERE id = $1 AND locked_by = $2 AND attempt_count = $3
  AND is_current AND status = 'running' AND locked_until > clock_timestamp()
FOR UPDATE
`

type LockGenerationJobClaimParams struct {
	ID           uuid.UUID `db:"id" json:"id"`
	WorkerID     *string   `db:"worker_id" json:"worker_id"`
	AttemptCount int32     `db:"attempt_count" json:"attempt_count"`
}

func (q *Queries) LockGenerationJobClaim(ctx context.Context, arg LockGenerationJobClaimParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockGenerationJobClaim, arg.ID, arg.WorkerID, arg.AttemptCount)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const markGenerationJobFailureHandled = `-- name: MarkGenerationJobFailureHandled :execrows
UPDATE generation_jobs AS job
SET failure_handled_at = $1,
    updated_at = GREATEST(job.updated_at, $1)
WHERE job.id = $2
  AND job.status = 'failed'
  AND job.failure_handled_at IS NULL
`

type MarkGenerationJobFailureHandledParams struct {
	HandledAt *time.Time `db:"handled_at" json:"handled_at"`
	ID        uuid.UUID  `db:"id" json:"id"`
}

func (q *Queries) MarkGenerationJobFailureHandled(ctx context.Context, arg MarkGenerationJobFailureHandledParams) (int64, error) {
	result, err := q.db.Exec(ctx, markGenerationJobFailureHandled, arg.HandledAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeTerminalGenerationJobsBefore = `-- name: PurgeTerminalGenerationJobsBefore :execrows
DELETE FROM generation_jobs WHERE id IN (
 SELECT j.id FROM generation_jobs j JOIN generation_requests r ON r.id = j.request_id
 WHERE (NOT j.is_current OR j.generation_attempt < r.generation_attempt)
 AND j.status IN ('completed', 'failed', 'cancelled') AND j.updated_at < $1
 AND NOT EXISTS (SELECT 1 FROM generation_jobs child WHERE child.parent_job_id = j.id)
 ORDER BY j.updated_at, j.id LIMIT $2
)
`

type PurgeTerminalGenerationJobsBeforeParams struct {
	Cutoff    time.Time `db:"cutoff" json:"cutoff"`
	LimitRows int32     `db:"limit_rows" json:"limit_rows"`
}

func (q *Queries) PurgeTerminalGenerationJobsBefore(ctx context.Context, arg PurgeTerminalGenerationJobsBeforeParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeTerminalGenerationJobsBefore, arg.Cutoff, arg.LimitRows)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renewGenerationJobLease = `-- name: RenewGenerationJobLease :execrows
UPDATE generation_jobs
SET
  locked_until = $1,
  updated_at = CURRENT_TIMESTAMP
WHERE id = $2
  AND status = 'running'
  AND locked_by = $3
  AND attempt_count = $4
  AND locked_until > CURRENT_TIMESTAMP
  AND $1 > CURRENT_TIMESTAMP
`

type RenewGenerationJobLeaseParams struct {
	LockedUntil  *time.Time `db:"locked_until" json:"locked_until"`
	ID           uuid.UUID  `db:"id" json:"id"`
	WorkerID     *string    `db:"worker_id" json:"worker_id"`
	AttemptCount int32      `db:"attempt_count" json:"attempt_count"`
}

func (q *Queries) RenewGenerationJobLease(ctx context.Context, arg RenewGenerationJobLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, renewGenerationJobLease,
		arg.LockedUntil,
		arg.ID,
		arg.WorkerID,
		arg.AttemptCount,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const requeueExpiredGenerationJobs = `-- name: RequeueExpiredGenerationJobs :execrows
WITH request_locks AS MATERIALIZED (
 SELECT r.id FROM generation_requests r WHERE EXISTS (
   SELECT 1 FROM generation_jobs j WHERE j.request_id = r.id AND j.status = 'running' AND j.locked_until <= $1
 ) ORDER BY r.id FOR UPDATE OF r
)
UPDATE generation_jobs
SET
  status = CASE
    WHEN attempt_count < max_attempts THEN 'retry_scheduled'::generation_job_status
    ELSE 'failed'::generation_job_status
  END,
  available_at = $1,
  locked_by = NULL,
  locked_until = NULL,
  completed_at = CASE WHEN attempt_count >= max_attempts THEN $1 ELSE NULL END,
  last_error_code = CASE
    WHEN attempt_count < max_attempts THEN 'lease_expired'
    ELSE 'max_attempts_exhausted'
  END,
  last_error_message = 'worker lease expired before the job completed',
  updated_at = $1
WHERE request_id IN (SELECT id FROM request_locks) AND status = 'running'
  AND locked_until <= $1
`

func (q *Queries) RequeueExpiredGenerationJobs(ctx context.Context, requeuedAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, requeueExpiredGenerationJobs, requeuedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryGenerationJob = `-- name: RetryGenerationJob :execrows
WITH request_lock AS MATERIALIZED (
 SELECT r.id FROM generation_requests r JOIN generation_jobs j ON j.request_id = r.id WHERE j.id = $4 FOR UPDATE OF r
)
UPDATE generation_jobs AS job
SET
  status = CASE
    WHEN attempt_count < max_attempts THEN 'retry_scheduled'::generation_job_status
    ELSE 'failed'::generation_job_status
  END,
  available_at = $1,
  locked_by = NULL,
  locked_until = NULL,
  completed_at = CASE WHEN attempt_count >= max_attempts THEN CURRENT_TIMESTAMP ELSE NULL END,
  last_error_code = CASE
    WHEN attempt_count < max_attempts THEN $2
    ELSE 'max_attempts_exhausted'
  END,
  last_error_message = $3,
  updated_at = CURRENT_TIMESTAMP
WHERE job.id = $4 AND job.request_id IN (SELECT id FROM request_lock)
  AND job.status = 'running'
  AND job.locked_by = $5
  AND job.attempt_count = $6
  AND job.locked_until > CURRENT_TIMESTAMP
`

type RetryGenerationJobParams struct {
	RetryAt      time.Time `db:"retry_at" json:"retry_at"`
	ErrorCode    *string   `db:"error_code" json:"error_code"`
	ErrorMessage *string   `db:"error_message" json:"error_message"`
	ID           uuid.UUID `db:"id" json:"id"`
	WorkerID     *string   `db:"worker_id" json:"worker_id"`
	AttemptCount int32     `db:"attempt_count" json:"attempt_count"`
}

func (q *Queries) RetryGenerationJob(ctx context.Context, arg RetryGenerationJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryGenerationJob,
		arg.RetryAt,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.ID,
		arg.WorkerID,
		arg.AttemptCount,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
