// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: generation_tracking.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCurrentGenerationOperation = `-- name: GetCurrentGenerationOperation :one
SELECT id, request_id, parent_job_id, kind, status, target_id, idempotency_key, payload, priority, attempt_count, max_attempts, available_at, locked_by, locked_until, started_at, completed_at, last_error_code, last_error_message, created_at, updated_at, failure_handled_at, generation_attempt, is_current, operation_version, supersedes_job_id FROM generation_jobs WHERE request_id = $1 AND generation_attempt = $2
AND kind = $3 AND target_id IS NOT DISTINCT FROM $4::uuid AND is_current
`

type GetCurrentGenerationOperationParams struct {
	RequestID         uuid.UUID         `db:"request_id" json:"request_id"`
	GenerationAttempt int32             `db:"generation_attempt" json:"generation_attempt"`
	Kind              GenerationJobKind `db:"kind" json:"kind"`
	TargetID          pgtype.UUID       `db:"target_id" json:"target_id"`
}

func (q *Queries) GetCurrentGenerationOperation(ctx context.Context, arg GetCurrentGenerationOperationParams) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, getCurrentGenerationOperation,
		arg.RequestID,
		arg.GenerationAttempt,
		arg.Kind,
		arg.TargetID,
	)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ParentJobID,
		&i.Kind,
		&i.Status,
		&i.TargetID,
		&i.IdempotencyKey,
		&i.Payload,
		&i.Priority,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.AvailableAt,
		&i.LockedBy,
		&i.LockedUntil,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailureHandledAt,
		&i.GenerationAttempt,
		&i.IsCurrent,
		&i.OperationVersion,
		&i.SupersedesJobID,
	)
	return i, err
}

const getGenerationRetryReceipt = `-- name: GetGenerationRetryReceipt :one
SELECT payload, result FROM generation_retry_commands WHERE request_id = $1 AND idempotency_key = $2
`

type GetGenerationRetryReceiptParams struct {
	RequestID      uuid.UUID `db:"request_id" json:"request_id"`
	IdempotencyKey string    `db:"idempotency_key" json:"idempotency_key"`
}

type GetGenerationRetryReceiptRow struct {
	Payload json.RawMessage `db:"payload" json:"payload"`
	Result  json.RawMessage `db:"result" json:"result"`
}

func (q *Queries) GetGenerationRetryReceipt(ctx context.Context, arg GetGenerationRetryReceiptParams) (GetGenerationRetryReceiptRow, error) {
	row := q.db.QueryRow(ctx, getGenerationRetryReceipt, arg.RequestID, arg.IdempotencyKey)
	var i GetGenerationRetryReceiptRow
	err := row.Scan(&i.Payload, &i.Result)
	return i, err
}

const getGenerationTrackingSnapshot = `-- name: GetGenerationTrackingSnapshot :one
SELECT jsonb_build_object(
  'requestId', r.id, 'generationAttempt', r.generation_attempt,
  'revision', r.tracking_revision::text, 'observedAt', clock_timestamp(),
  'pipelineStatus', r.pipeline_status, 'title', COALESCE(c.title, r.suggested_title, ''),
  'courseId', c.id, 'createdAt', r.created_at AT TIME ZONE 'UTC',
  'completedAt', r.completed_at AT TIME ZONE 'UTC',
  'isOutOfScope', r.is_out_of_scope, 'historyComplete', r.history_complete,
  'contentComplete', COALESCE(cs.content_complete, false),
  'modules', COALESCE((SELECT jsonb_agg(jsonb_build_object(
    'id', m.id, 'title', m.title, 'order', m.module_order,
    'lessons', COALESCE((SELECT jsonb_agg(jsonb_build_object(
      'id', l.id, 'title', l.title, 'order', l.lesson_order,
      'hasContent', (COALESCE(btrim(l.content_markdown), '') <> ''
        OR EXISTS (SELECT 1 FROM lesson_exercises e WHERE e.lesson_id = l.id)
        OR EXISTS (SELECT 1 FROM lesson_quizzes q WHERE q.lesson_id = l.id))
    ) ORDER BY l.lesson_order) FROM lessons l WHERE l.module_id = m.id), '[]'::jsonb)
  ) ORDER BY m.module_order) FROM modules m WHERE m.course_id = c.id), '[]'::jsonb),
  'operations', COALESCE((SELECT jsonb_agg(jsonb_build_object(
    'id', j.id, 'parentJobId', j.parent_job_id, 'targetId', j.target_id,
    'kind', j.kind, 'status', j.status, 'operationVersion', j.operation_version,
    'supersedesJobId', j.supersedes_job_id, 'attemptCount', j.attempt_count,
    'maxAttempts', j.max_attempts, 'availableAt', j.available_at,
    'startedAt', j.started_at, 'completedAt', j.completed_at,
    'failureCode', CASE
      WHEN j.status = 'cancelled' THEN 'cancelled'
      WHEN j.status NOT IN ('failed', 'retry_scheduled') THEN NULL
      WHEN j.last_error_code IN ('invalid_command', 'invalid_api_key', 'insufficient_quota', 'model_not_found', 'invalid_request_error', 'openai_http_400', 'openai_http_401', 'openai_http_403', 'openai_http_404') THEN 'operator_action_required'
      WHEN j.status = 'failed' AND j.attempt_count >= j.max_attempts THEN 'retry_exhausted'
      ELSE 'generation_failed' END
  ) ORDER BY j.created_at, j.id) FROM generation_jobs j
    WHERE j.request_id = r.id AND j.generation_attempt = r.generation_attempt AND j.is_current), '[]'::jsonb)
)::jsonb AS snapshot
FROM generation_requests r LEFT JOIN courses c ON c.request_id = r.id
LEFT JOIN course_content_states cs ON cs.course_id = c.id WHERE r.id = $1
`

func (q *Queries) GetGenerationTrackingSnapshot(ctx context.Context, requestID uuid.UUID) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, getGenerationTrackingSnapshot, requestID)
	var snapshot json.RawMessage
	err := row.Scan(&snapshot)
	return snapshot, err
}

const listPublicGenerationEvents = `-- name: ListPublicGenerationEvents :many
SELECT id, generation_attempt, job_id, kind, status, target_id, operation_version, attempt_count, occurred_at
FROM generation_events WHERE request_id = $1 AND ($2::bigint = 0 OR id < $2)
ORDER BY id DESC LIMIT $3
`

type ListPublicGenerationEventsParams struct {
	RequestID uuid.UUID `db:"request_id" json:"request_id"`
	CursorID  int64     `db:"cursor_id" json:"cursor_id"`
	LimitRows int32     `db:"limit_rows" json:"limit_rows"`
}

type ListPublicGenerationEventsRow struct {
	ID                int64       `db:"id" json:"id"`
	GenerationAttempt int32       `db:"generation_attempt" json:"generation_attempt"`
	JobID             pgtype.UUID `db:"job_id" json:"job_id"`
	Kind              string      `db:"kind" json:"kind"`
	Status            string      `db:"status" json:"status"`
	TargetID          pgtype.UUID `db:"target_id" json:"target_id"`
	OperationVersion  *int32      `db:"operation_version" json:"operation_version"`
	AttemptCount      *int32      `db:"attempt_count" json:"attempt_count"`
	OccurredAt        time.Time   `db:"occurred_at" json:"occurred_at"`
}

func (q *Queries) ListPublicGenerationEvents(ctx context.Context, arg ListPublicGenerationEventsParams) ([]ListPublicGenerationEventsRow, error) {
	rows, err := q.db.Query(ctx, listPublicGenerationEvents, arg.RequestID, arg.CursorID, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicGenerationEventsRow{}
	for rows.Next() {
		var i ListPublicGenerationEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.GenerationAttempt,
			&i.JobID,
			&i.Kind,
			&i.Status,
			&i.TargetID,
			&i.OperationVersion,
			&i.AttemptCount,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeGenerationRetryReceiptsBefore = `-- name: PurgeGenerationRetryReceiptsBefore :execrows
DELETE FROM generation_retry_commands WHERE (request_id, idempotency_key) IN (
 SELECT receipt.request_id, receipt.idempotency_key FROM generation_retry_commands receipt WHERE receipt.created_at < $1
 ORDER BY receipt.created_at LIMIT $2
)
`

type PurgeGenerationRetryReceiptsBeforeParams struct {
	Cutoff    time.Time `db:"cutoff" json:"cutoff"`
	LimitRows int32     `db:"limit_rows" json:"limit_rows"`
}

func (q *Queries) PurgeGenerationRetryReceiptsBefore(ctx context.Context, arg PurgeGenerationRetryReceiptsBeforeParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeGenerationRetryReceiptsBefore, arg.Cutoff, arg.LimitRows)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgePublicGenerationEventsBefore = `-- name: PurgePublicGenerationEventsBefore :execrows
WITH candidates AS MATERIALIZED (
  SELECT e.id, e.request_id FROM generation_events e WHERE e.occurred_at < $1
  ORDER BY e.occurred_at, e.id LIMIT $2
), request_locks AS MATERIALIZED (
  SELECT r.id FROM generation_requests r WHERE r.id IN (SELECT request_id FROM candidates)
  ORDER BY r.id FOR UPDATE
), removed AS (
  DELETE FROM generation_events WHERE id IN (SELECT id FROM candidates)
    AND request_id IN (SELECT id FROM request_locks) RETURNING request_id
)
UPDATE generation_requests SET history_complete = false, tracking_revision = tracking_revision + 1
WHERE id IN (SELECT request_id FROM removed)
`

type PurgePublicGenerationEventsBeforeParams struct {
	Cutoff    time.Time `db:"cutoff" json:"cutoff"`
	LimitRows int32     `db:"limit_rows" json:"limit_rows"`
}

func (q *Queries) PurgePublicGenerationEventsBefore(ctx context.Context, arg PurgePublicGenerationEventsBeforeParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgePublicGenerationEventsBefore, arg.Cutoff, arg.LimitRows)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveGenerationRetryReceipt = `-- name: SaveGenerationRetryReceipt :exec
INSERT INTO generation_retry_commands(request_id, idempotency_key, payload, result)
VALUES ($1, $2, $3, $4)
`

type SaveGenerationRetryReceiptParams struct {
	RequestID      uuid.UUID       `db:"request_id" json:"request_id"`
	IdempotencyKey string          `db:"idempotency_key" json:"idempotency_key"`
	Payload        json.RawMessage `db:"payload" json:"payload"`
	Result         json.RawMessage `db:"result" json:"result"`
}

func (q *Queries) SaveGenerationRetryReceipt(ctx context.Context, arg SaveGenerationRetryReceiptParams) error {
	_, err := q.db.Exec(ctx, saveGenerationRetryReceipt,
		arg.RequestID,
		arg.IdempotencyKey,
		arg.Payload,
		arg.Result,
	)
	return err
}

const supersedeGenerationOperation = `-- name: SupersedeGenerationOperation :execrows
UPDATE generation_jobs SET is_current = false
WHERE id = $1 AND operation_version = $2 AND is_current
  AND status IN ('failed', 'cancelled')
`

type SupersedeGenerationOperationParams struct {
	ID               uuid.UUID `db:"id" json:"id"`
	OperationVersion int32     `db:"operation_version" json:"operation_version"`
}

func (q *Queries) SupersedeGenerationOperation(ctx context.Context, arg SupersedeGenerationOperationParams) (int64, error) {
	result, err := q.db.Exec(ctx, supersedeGenerationOperation, arg.ID, arg.OperationVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
