// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lessons.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createLesson = `-- name: CreateLesson :one
INSERT INTO lessons (
  id,
  module_id,
  lesson_order,
  title,
  type,
  estimated_duration_minutes,
  learning_goal,
  requires_diagram,
  technical_keywords,
  content_markdown,
  raw_content_output,
  created_at,
  updated_at
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5::lesson_type,
  $6,
  $7,
  $8,
  $9::jsonb,
  $10,
  $11::jsonb,
  $12,
  $13
)
RETURNING
  id,
  module_id,
  lesson_order,
  title,
  type,
  estimated_duration_minutes,
  learning_goal,
  requires_diagram,
  technical_keywords,
  content_markdown,
  raw_content_output,
  created_at,
  updated_at
`

type CreateLessonParams struct {
	ID                       uuid.UUID       `db:"id" json:"id"`
	ModuleID                 uuid.UUID       `db:"module_id" json:"module_id"`
	LessonOrder              int32           `db:"lesson_order" json:"lesson_order"`
	Title                    string          `db:"title" json:"title"`
	Type                     LessonType      `db:"type" json:"type"`
	EstimatedDurationMinutes int32           `db:"estimated_duration_minutes" json:"estimated_duration_minutes"`
	LearningGoal             string          `db:"learning_goal" json:"learning_goal"`
	RequiresDiagram          bool            `db:"requires_diagram" json:"requires_diagram"`
	TechnicalKeywords        json.RawMessage `db:"technical_keywords" json:"technical_keywords"`
	ContentMarkdown          *string         `db:"content_markdown" json:"content_markdown"`
	RawContentOutput         json.RawMessage `db:"raw_content_output" json:"raw_content_output"`
	CreatedAt                time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt                time.Time       `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateLesson(ctx context.Context, arg CreateLessonParams) (Lesson, error) {
	row := q.db.QueryRow(ctx, createLesson,
		arg.ID,
		arg.ModuleID,
		arg.LessonOrder,
		arg.Title,
		arg.Type,
		arg.EstimatedDurationMinutes,
		arg.LearningGoal,
		arg.RequiresDiagram,
		arg.TechnicalKeywords,
		arg.ContentMarkdown,
		arg.RawContentOutput,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.LessonOrder,
		&i.Title,
		&i.Type,
		&i.EstimatedDurationMinutes,
		&i.LearningGoal,
		&i.RequiresDiagram,
		&i.TechnicalKeywords,
		&i.ContentMarkdown,
		&i.RawContentOutput,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

type CreateLessonsParams struct {
	ID                       uuid.UUID       `db:"id" json:"id"`
	ModuleID                 uuid.UUID       `db:"module_id" json:"module_id"`
	LessonOrder              int32           `db:"lesson_order" json:"lesson_order"`
	Title                    string          `db:"title" json:"title"`
	Type                     LessonType      `db:"type" json:"type"`
	EstimatedDurationMinutes int32           `db:"estimated_duration_minutes" json:"estimated_duration_minutes"`
	LearningGoal             string          `db:"learning_goal" json:"learning_goal"`
	RequiresDiagram          bool            `db:"requires_diagram" json:"requires_diagram"`
	TechnicalKeywords        json.RawMessage `db:"technical_keywords" json:"technical_keywords"`
	ContentMarkdown          *string         `db:"content_markdown" json:"content_markdown"`
	RawContentOutput         json.RawMessage `db:"raw_content_output" json:"raw_content_output"`
	CreatedAt                time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt                time.Time       `db:"updated_at" json:"updated_at"`
}

const deleteLessonByID = `-- name: DeleteLessonByID :execrows
DELETE FROM lessons
WHERE id = $1
`

type DeleteLessonByIDParams struct {
	ID uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) DeleteLessonByID(ctx context.Context, arg DeleteLessonByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLessonByID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLessonByID = `-- name: GetLessonByID :one
SELECT
  id,
  module_id,
  lesson_order,
  title,
  type,
  estimated_duration_minutes,
  learning_goal,
  requires_diagram,
  technical_keywords,
  content_markdown,
  raw_content_output,
  created_at,
  updated_at
FROM lessons
WHERE id = $1
`

type GetLessonByIDParams struct {
	ID uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetLessonByID(ctx context.Context, arg GetLessonByIDParams) (Lesson, error) {
	row := q.db.QueryRow(ctx, getLessonByID, arg.ID)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.LessonOrder,
		&i.Title,
		&i.Type,
		&i.EstimatedDurationMinutes,
		&i.LearningGoal,
		&i.RequiresDiagram,
		&i.TechnicalKeywords,
		&i.ContentMarkdown,
		&i.RawContentOutput,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLessonsByModuleID = `-- name: ListLessonsByModuleID :many
SELECT
  id,
  module_id,
  lesson_order,
  title,
  type,
  estimated_duration_minutes,
  learning_goal,
  requires_diagram,
  technical_keywords,
  content_markdown,
  raw_content_output,
  created_at,
  updated_at
FROM lessons
WHERE module_id = $1
ORDER BY lesson_order ASC, id ASC
`

type ListLessonsByModuleIDParams struct {
	ModuleID uuid.UUID `db:"module_id" json:"module_id"`
}

func (q *Queries) ListLessonsByModuleID(ctx context.Context, arg ListLessonsByModuleIDParams) ([]Lesson, error) {
	rows, err := q.db.Query(ctx, listLessonsByModuleID, arg.ModuleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lesson{}
	for rows.Next() {
		var i Lesson
		if err := rows.Scan(
			&i.ID,
			&i.ModuleID,
			&i.LessonOrder,
			&i.Title,
			&i.Type,
			&i.EstimatedDurationMinutes,
			&i.LearningGoal,
			&i.RequiresDiagram,
			&i.TechnicalKeywords,
			&i.ContentMarkdown,
			&i.RawContentOutput,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLessonsByModuleIDs = `-- name: ListLessonsByModuleIDs :many
SELECT
  id,
  module_id,
  lesson_order,
  title,
  type,
  estimated_duration_minutes,
  learning_goal,
  requires_diagram,
  technical_keywords,
  content_markdown,
  raw_content_output,
  created_at,
  updated_at
FROM lessons
WHERE module_id = ANY($1::uuid[])
ORDER BY module_id ASC, lesson_order ASC, id ASC
`

type ListLessonsByModuleIDsParams struct {
	ModuleIds []uuid.UUID `db:"module_ids" json:"module_ids"`
}

func (q *Queries) ListLessonsByModuleIDs(ctx context.Context, arg ListLessonsByModuleIDsParams) ([]Lesson, error) {
	rows, err := q.db.Query(ctx, listLessonsByModuleIDs, arg.ModuleIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lesson{}
	for rows.Next() {
		var i Lesson
		if err := rows.Scan(
			&i.ID,
			&i.ModuleID,
			&i.LessonOrder,
			&i.Title,
			&i.Type,
			&i.EstimatedDurationMinutes,
			&i.LearningGoal,
			&i.RequiresDiagram,
			&i.TechnicalKeywords,
			&i.ContentMarkdown,
			&i.RawContentOutput,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceLessonContent = `-- name: ReplaceLessonContent :one
WITH deleted_exercises AS (
  DELETE FROM lesson_exercises
  WHERE lesson_id = $4
), deleted_quizzes AS (
  DELETE FROM lesson_quizzes
  WHERE lesson_id = $4
)
UPDATE lessons AS l
SET
  content_markdown = $1,
  raw_content_output = $2::jsonb,
  updated_at = $3
WHERE l.id = $4
RETURNING
  l.id,
  l.module_id,
  l.lesson_order,
  l.title,
  l.type,
  l.estimated_duration_minutes,
  l.learning_goal,
  l.requires_diagram,
  l.technical_keywords,
  l.content_markdown,
  l.raw_content_output,
  l.created_at,
  l.updated_at
`

type ReplaceLessonContentParams struct {
	ContentMarkdown  *string         `db:"content_markdown" json:"content_markdown"`
	RawContentOutput json.RawMessage `db:"raw_content_output" json:"raw_content_output"`
	UpdatedAt        time.Time       `db:"updated_at" json:"updated_at"`
	ID               uuid.UUID       `db:"id" json:"id"`
}

func (q *Queries) ReplaceLessonContent(ctx context.Context, arg ReplaceLessonContentParams) (Lesson, error) {
	row := q.db.QueryRow(ctx, replaceLessonContent,
		arg.ContentMarkdown,
		arg.RawContentOutput,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.LessonOrder,
		&i.Title,
		&i.Type,
		&i.EstimatedDurationMinutes,
		&i.LearningGoal,
		&i.RequiresDiagram,
		&i.TechnicalKeywords,
		&i.ContentMarkdown,
		&i.RawContentOutput,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLesson = `-- name: UpdateLesson :one
UPDATE lessons AS l
SET
  module_id = $1,
  lesson_order = $2,
  title = $3,
  type = $4::lesson_type,
  estimated_duration_minutes = $5,
  learning_goal = $6,
  requires_diagram = $7,
  technical_keywords = $8::jsonb,
  content_markdown = $9,
  raw_content_output = $10::jsonb,
  updated_at = $11
WHERE l.id = $12
RETURNING
  l.id,
  l.module_id,
  l.lesson_order,
  l.title,
  l.type,
  l.estimated_duration_minutes,
  l.learning_goal,
  l.requires_diagram,
  l.technical_keywords,
  l.content_markdown,
  l.raw_content_output,
  l.created_at,
  l.updated_at
`

type UpdateLessonParams struct {
	ModuleID                 uuid.UUID       `db:"module_id" json:"module_id"`
	LessonOrder              int32           `db:"lesson_order" json:"lesson_order"`
	Title                    string          `db:"title" json:"title"`
	Type                     LessonType      `db:"type" json:"type"`
	EstimatedDurationMinutes int32           `db:"estimated_duration_minutes" json:"estimated_duration_minutes"`
	LearningGoal             string          `db:"learning_goal" json:"learning_goal"`
	RequiresDiagram          bool            `db:"requires_diagram" json:"requires_diagram"`
	TechnicalKeywords        json.RawMessage `db:"technical_keywords" json:"technical_keywords"`
	ContentMarkdown          *string         `db:"content_markdown" json:"content_markdown"`
	RawContentOutput         json.RawMessage `db:"raw_content_output" json:"raw_content_output"`
	UpdatedAt                time.Time       `db:"updated_at" json:"updated_at"`
	ID                       uuid.UUID       `db:"id" json:"id"`
}

func (q *Queries) UpdateLesson(ctx context.Context, arg UpdateLessonParams) (Lesson, error) {
	row := q.db.QueryRow(ctx, updateLesson,
		arg.ModuleID,
		arg.LessonOrder,
		arg.Title,
		arg.Type,
		arg.EstimatedDurationMinutes,
		arg.LearningGoal,
		arg.RequiresDiagram,
		arg.TechnicalKeywords,
		arg.ContentMarkdown,
		arg.RawContentOutput,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.LessonOrder,
		&i.Title,
		&i.Type,
		&i.EstimatedDurationMinutes,
		&i.LearningGoal,
		&i.RequiresDiagram,
		&i.TechnicalKeywords,
		&i.ContentMarkdown,
		&i.RawContentOutput,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
