// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityDifficulty string

const (
	ActivityDifficultyBeginner     ActivityDifficulty = "beginner"
	ActivityDifficultyIntermediate ActivityDifficulty = "intermediate"
	ActivityDifficultyAdvanced     ActivityDifficulty = "advanced"
)

func (e *ActivityDifficulty) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ActivityDifficulty(s)
	case string:
		*e = ActivityDifficulty(s)
	default:
		return fmt.Errorf("unsupported scan type for ActivityDifficulty: %T", src)
	}
	return nil
}

type NullActivityDifficulty struct {
	ActivityDifficulty ActivityDifficulty `json:"activity_difficulty"`
	Valid              bool               `json:"valid"` // Valid is true if ActivityDifficulty is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullActivityDifficulty) Scan(value interface{}) error {
	if value == nil {
		ns.ActivityDifficulty, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ActivityDifficulty.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullActivityDifficulty) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ActivityDifficulty), nil
}

type CourseGenerationStatus string

const (
	CourseGenerationStatusAnalysisPending        CourseGenerationStatus = "analysis_pending"
	CourseGenerationStatusAnalysisCompleted      CourseGenerationStatus = "analysis_completed"
	CourseGenerationStatusArchitectureGenerating CourseGenerationStatus = "architecture_generating"
	CourseGenerationStatusStructureGenerated     CourseGenerationStatus = "structure_generated"
	CourseGenerationStatusLessonsGenerating      CourseGenerationStatus = "lessons_generating"
	CourseGenerationStatusLessonsGenerated       CourseGenerationStatus = "lessons_generated"
	CourseGenerationStatusContentGenerating      CourseGenerationStatus = "content_generating"
	CourseGenerationStatusCompleted              CourseGenerationStatus = "completed"
	CourseGenerationStatusFailed                 CourseGenerationStatus = "failed"
)

func (e *CourseGenerationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CourseGenerationStatus(s)
	case string:
		*e = CourseGenerationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CourseGenerationStatus: %T", src)
	}
	return nil
}

type NullCourseGenerationStatus struct {
	CourseGenerationStatus CourseGenerationStatus `json:"course_generation_status"`
	Valid                  bool                   `json:"valid"` // Valid is true if CourseGenerationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCourseGenerationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CourseGenerationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CourseGenerationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCourseGenerationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CourseGenerationStatus), nil
}

type CourseLanguage string

const (
	CourseLanguageFr CourseLanguage = "fr"
	CourseLanguageEn CourseLanguage = "en"
)

func (e *CourseLanguage) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CourseLanguage(s)
	case string:
		*e = CourseLanguage(s)
	default:
		return fmt.Errorf("unsupported scan type for CourseLanguage: %T", src)
	}
	return nil
}

type NullCourseLanguage struct {
	CourseLanguage CourseLanguage `json:"course_language"`
	Valid          bool           `json:"valid"` // Valid is true if CourseLanguage is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCourseLanguage) Scan(value interface{}) error {
	if value == nil {
		ns.CourseLanguage, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CourseLanguage.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCourseLanguage) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CourseLanguage), nil
}

type ExerciseType string

const (
	ExerciseTypeGuidedLab     ExerciseType = "guided_lab"
	ExerciseTypeCoding        ExerciseType = "coding"
	ExerciseTypeDebugging     ExerciseType = "debugging"
	ExerciseTypeConfiguration ExerciseType = "configuration"
	ExerciseTypeScenario      ExerciseType = "scenario"
	ExerciseTypeWrittenAnswer ExerciseType = "written_answer"
	ExerciseTypeCommandLine   ExerciseType = "command_line"
	ExerciseTypeMixed         ExerciseType = "mixed"
)

func (e *ExerciseType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExerciseType(s)
	case string:
		*e = ExerciseType(s)
	default:
		return fmt.Errorf("unsupported scan type for ExerciseType: %T", src)
	}
	return nil
}

type NullExerciseType struct {
	ExerciseType ExerciseType `json:"exercise_type"`
	Valid        bool         `json:"valid"` // Valid is true if ExerciseType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExerciseType) Scan(value interface{}) error {
	if value == nil {
		ns.ExerciseType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExerciseType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExerciseType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExerciseType), nil
}

type GenerationJobKind string

const (
	GenerationJobKindAnalysis       GenerationJobKind = "analysis"
	GenerationJobKindArchitecture   GenerationJobKind = "architecture"
	GenerationJobKindLessonPlan     GenerationJobKind = "lesson_plan"
	GenerationJobKindLessonContent  GenerationJobKind = "lesson_content"
	GenerationJobKindModuleContent  GenerationJobKind = "module_content"
	GenerationJobKindFinalizeCourse GenerationJobKind = "finalize_course"
)

func (e *GenerationJobKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GenerationJobKind(s)
	case string:
		*e = GenerationJobKind(s)
	default:
		return fmt.Errorf("unsupported scan type for GenerationJobKind: %T", src)
	}
	return nil
}

type NullGenerationJobKind struct {
	GenerationJobKind GenerationJobKind `json:"generation_job_kind"`
	Valid             bool              `json:"valid"` // Valid is true if GenerationJobKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGenerationJobKind) Scan(value interface{}) error {
	if value == nil {
		ns.GenerationJobKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GenerationJobKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGenerationJobKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GenerationJobKind), nil
}

type GenerationJobStatus string

const (
	GenerationJobStatusQueued         GenerationJobStatus = "queued"
	GenerationJobStatusRunning        GenerationJobStatus = "running"
	GenerationJobStatusRetryScheduled GenerationJobStatus = "retry_scheduled"
	GenerationJobStatusCompleted      GenerationJobStatus = "completed"
	GenerationJobStatusFailed         GenerationJobStatus = "failed"
	GenerationJobStatusCancelled      GenerationJobStatus = "cancelled"
)

func (e *GenerationJobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GenerationJobStatus(s)
	case string:
		*e = GenerationJobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for GenerationJobStatus: %T", src)
	}
	return nil
}

type NullGenerationJobStatus struct {
	GenerationJobStatus GenerationJobStatus `json:"generation_job_status"`
	Valid               bool                `json:"valid"` // Valid is true if GenerationJobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGenerationJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.GenerationJobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GenerationJobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGenerationJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GenerationJobStatus), nil
}

type GenerationPipelineStatus string

const (
	GenerationPipelineStatusQueued                GenerationPipelineStatus = "queued"
	GenerationPipelineStatusRunning               GenerationPipelineStatus = "running"
	GenerationPipelineStatusAwaitingClarification GenerationPipelineStatus = "awaiting_clarification"
	GenerationPipelineStatusCompleted             GenerationPipelineStatus = "completed"
	GenerationPipelineStatusFailed                GenerationPipelineStatus = "failed"
)

func (e *GenerationPipelineStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GenerationPipelineStatus(s)
	case string:
		*e = GenerationPipelineStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for GenerationPipelineStatus: %T", src)
	}
	return nil
}

type NullGenerationPipelineStatus struct {
	GenerationPipelineStatus GenerationPipelineStatus `json:"generation_pipeline_status"`
	Valid                    bool                     `json:"valid"` // Valid is true if GenerationPipelineStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGenerationPipelineStatus) Scan(value interface{}) error {
	if value == nil {
		ns.GenerationPipelineStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GenerationPipelineStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGenerationPipelineStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GenerationPipelineStatus), nil
}

type LessonType string

const (
	LessonTypeTheory   LessonType = "theory"
	LessonTypePractice LessonType = "practice"
	LessonTypeMixed    LessonType = "mixed"
	LessonTypeQuiz     LessonType = "quiz"
)

func (e *LessonType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LessonType(s)
	case string:
		*e = LessonType(s)
	default:
		return fmt.Errorf("unsupported scan type for LessonType: %T", src)
	}
	return nil
}

type NullLessonType struct {
	LessonType LessonType `json:"lesson_type"`
	Valid      bool       `json:"valid"` // Valid is true if LessonType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLessonType) Scan(value interface{}) error {
	if value == nil {
		ns.LessonType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LessonType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLessonType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LessonType), nil
}

type Level string

const (
	LevelBeginner     Level = "beginner"
	LevelIntermediate Level = "intermediate"
	LevelAdvanced     Level = "advanced"
	LevelExpert       Level = "expert"
	LevelUnknown      Level = "unknown"
)

func (e *Level) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Level(s)
	case string:
		*e = Level(s)
	default:
		return fmt.Errorf("unsupported scan type for Level: %T", src)
	}
	return nil
}

type NullLevel struct {
	Level Level `json:"level"`
	Valid bool  `json:"valid"` // Valid is true if Level is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLevel) Scan(value interface{}) error {
	if value == nil {
		ns.Level, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Level.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Level), nil
}

type QuizType string

const (
	QuizTypeSingleChoice   QuizType = "single_choice"
	QuizTypeMultipleChoice QuizType = "multiple_choice"
	QuizTypeTrueFalse      QuizType = "true_false"
	QuizTypeShortAnswer    QuizType = "short_answer"
	QuizTypeMixed          QuizType = "mixed"
)

func (e *QuizType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = QuizType(s)
	case string:
		*e = QuizType(s)
	default:
		return fmt.Errorf("unsupported scan type for QuizType: %T", src)
	}
	return nil
}

type NullQuizType struct {
	QuizType QuizType `json:"quiz_type"`
	Valid    bool     `json:"valid"` // Valid is true if QuizType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullQuizType) Scan(value interface{}) error {
	if value == nil {
		ns.QuizType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.QuizType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullQuizType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.QuizType), nil
}

type Course struct {
	ID                      uuid.UUID              `db:"id" json:"id"`
	RequestID               uuid.UUID              `db:"request_id" json:"request_id"`
	Language                CourseLanguage         `db:"language" json:"language"`
	Status                  CourseGenerationStatus `db:"status" json:"status"`
	InitialUserPrompt       string                 `db:"initial_user_prompt" json:"initial_user_prompt"`
	Title                   string                 `db:"title" json:"title"`
	Synopsis                string                 `db:"synopsis" json:"synopsis"`
	TargetAudience          *string                `db:"target_audience" json:"target_audience"`
	CurrentLevel            Level                  `db:"current_level" json:"current_level"`
	TargetLevel             Level                  `db:"target_level" json:"target_level"`
	Prerequisites           json.RawMessage        `db:"prerequisites" json:"prerequisites"`
	Goals                   json.RawMessage        `db:"goals" json:"goals"`
	AcquiredSkills          json.RawMessage        `db:"acquired_skills" json:"acquired_skills"`
	FinalProjectTitle       *string                `db:"final_project_title" json:"final_project_title"`
	FinalProjectDescription *string                `db:"final_project_description" json:"final_project_description"`
	FinalProjectConstraints json.RawMessage        `db:"final_project_constraints" json:"final_project_constraints"`
	GenerationPayload       json.RawMessage        `db:"generation_payload" json:"generation_payload"`
	RawArchitectureOutput   json.RawMessage        `db:"raw_architecture_output" json:"raw_architecture_output"`
	CreatedAt               time.Time              `db:"created_at" json:"created_at"`
	UpdatedAt               time.Time              `db:"updated_at" json:"updated_at"`
}

type GenerationJob struct {
	ID               uuid.UUID           `db:"id" json:"id"`
	RequestID        uuid.UUID           `db:"request_id" json:"request_id"`
	ParentJobID      pgtype.UUID         `db:"parent_job_id" json:"parent_job_id"`
	Kind             GenerationJobKind   `db:"kind" json:"kind"`
	Status           GenerationJobStatus `db:"status" json:"status"`
	TargetID         pgtype.UUID         `db:"target_id" json:"target_id"`
	IdempotencyKey   string              `db:"idempotency_key" json:"idempotency_key"`
	Payload          json.RawMessage     `db:"payload" json:"payload"`
	Priority         int32               `db:"priority" json:"priority"`
	AttemptCount     int32               `db:"attempt_count" json:"attempt_count"`
	MaxAttempts      int32               `db:"max_attempts" json:"max_attempts"`
	AvailableAt      time.Time           `db:"available_at" json:"available_at"`
	LockedBy         *string             `db:"locked_by" json:"locked_by"`
	LockedUntil      *time.Time          `db:"locked_until" json:"locked_until"`
	StartedAt        *time.Time          `db:"started_at" json:"started_at"`
	CompletedAt      *time.Time          `db:"completed_at" json:"completed_at"`
	LastErrorCode    *string             `db:"last_error_code" json:"last_error_code"`
	LastErrorMessage *string             `db:"last_error_message" json:"last_error_message"`
	CreatedAt        time.Time           `db:"created_at" json:"created_at"`
	UpdatedAt        time.Time           `db:"updated_at" json:"updated_at"`
}

type GenerationRequest struct {
	ID                        uuid.UUID                `db:"id" json:"id"`
	InitialUserPrompt         string                   `db:"initial_user_prompt" json:"initial_user_prompt"`
	PipelineStatus            GenerationPipelineStatus `db:"pipeline_status" json:"pipeline_status"`
	CurrentStep               *string                  `db:"current_step" json:"current_step"`
	ProgressPercent           int32                    `db:"progress_percent" json:"progress_percent"`
	FailureMessage            *string                  `db:"failure_message" json:"failure_message"`
	StartedAt                 *time.Time               `db:"started_at" json:"started_at"`
	CompletedAt               *time.Time               `db:"completed_at" json:"completed_at"`
	IsOutOfScope              bool                     `db:"is_out_of_scope" json:"is_out_of_scope"`
	ErrorMessage              *string                  `db:"error_message" json:"error_message"`
	WarningMessage            *string                  `db:"warning_message" json:"warning_message"`
	SuggestedTitle            *string                  `db:"suggested_title" json:"suggested_title"`
	ShortSynopsis             *string                  `db:"short_synopsis" json:"short_synopsis"`
	DetectedCurrentLevel      *Level                   `db:"detected_current_level" json:"detected_current_level"`
	DetectedTargetLevel       *Level                   `db:"detected_target_level" json:"detected_target_level"`
	DetectedGoal              *string                  `db:"detected_goal" json:"detected_goal"`
	DetectedLanguage          *CourseLanguage          `db:"detected_language" json:"detected_language"`
	ClarificationQuestions    json.RawMessage          `db:"clarification_questions" json:"clarification_questions"`
	RawAnalysisOutput         json.RawMessage          `db:"raw_analysis_output" json:"raw_analysis_output"`
	CreatedAt                 time.Time                `db:"created_at" json:"created_at"`
	UpdatedAt                 time.Time                `db:"updated_at" json:"updated_at"`
	AnalysisCompletedAt       *time.Time               `db:"analysis_completed_at" json:"analysis_completed_at"`
	ClarificationAnswers      json.RawMessage          `db:"clarification_answers" json:"clarification_answers"`
	ConfirmedTitle            *string                  `db:"confirmed_title" json:"confirmed_title"`
	ConfirmedSynopsis         *string                  `db:"confirmed_synopsis" json:"confirmed_synopsis"`
	ConfirmedCurrentLevel     *Level                   `db:"confirmed_current_level" json:"confirmed_current_level"`
	ConfirmedTargetLevel      *Level                   `db:"confirmed_target_level" json:"confirmed_target_level"`
	ConfirmedGoals            json.RawMessage          `db:"confirmed_goals" json:"confirmed_goals"`
	ConfirmedLanguage         *CourseLanguage          `db:"confirmed_language" json:"confirmed_language"`
	BriefConfirmedAt          *time.Time               `db:"brief_confirmed_at" json:"brief_confirmed_at"`
	ClarificationsSubmittedAt *time.Time               `db:"clarifications_submitted_at" json:"clarifications_submitted_at"`
	ClarificationVersion      int32                    `db:"clarification_version" json:"clarification_version"`
}

type Lesson struct {
	ID                       uuid.UUID       `db:"id" json:"id"`
	ModuleID                 uuid.UUID       `db:"module_id" json:"module_id"`
	LessonOrder              int32           `db:"lesson_order" json:"lesson_order"`
	Title                    string          `db:"title" json:"title"`
	Type                     LessonType      `db:"type" json:"type"`
	EstimatedDurationMinutes int32           `db:"estimated_duration_minutes" json:"estimated_duration_minutes"`
	LearningGoal             string          `db:"learning_goal" json:"learning_goal"`
	RequiresDiagram          bool            `db:"requires_diagram" json:"requires_diagram"`
	TechnicalKeywords        json.RawMessage `db:"technical_keywords" json:"technical_keywords"`
	ContentMarkdown          *string         `db:"content_markdown" json:"content_markdown"`
	RawContentOutput         json.RawMessage `db:"raw_content_output" json:"raw_content_output"`
	CreatedAt                time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt                time.Time       `db:"updated_at" json:"updated_at"`
}

type LessonExercise struct {
	ID                   uuid.UUID          `db:"id" json:"id"`
	LessonID             uuid.UUID          `db:"lesson_id" json:"lesson_id"`
	Type                 ExerciseType       `db:"type" json:"type"`
	Difficulty           ActivityDifficulty `db:"difficulty" json:"difficulty"`
	Title                string             `db:"title" json:"title"`
	Objective            string             `db:"objective" json:"objective"`
	InstructionsMarkdown string             `db:"instructions_markdown" json:"instructions_markdown"`
	ContentMarkdown      string             `db:"content_markdown" json:"content_markdown"`
	CorrectionMarkdown   string             `db:"correction_markdown" json:"correction_markdown"`
	Payload              json.RawMessage    `db:"payload" json:"payload"`
	RawAiOutput          json.RawMessage    `db:"raw_ai_output" json:"raw_ai_output"`
	CreatedAt            time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt            time.Time          `db:"updated_at" json:"updated_at"`
}

type LessonQuiz struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	LessonID    uuid.UUID          `db:"lesson_id" json:"lesson_id"`
	Type        QuizType           `db:"type" json:"type"`
	Difficulty  ActivityDifficulty `db:"difficulty" json:"difficulty"`
	Title       string             `db:"title" json:"title"`
	Objective   string             `db:"objective" json:"objective"`
	Questions   json.RawMessage    `db:"questions" json:"questions"`
	RawAiOutput json.RawMessage    `db:"raw_ai_output" json:"raw_ai_output"`
	CreatedAt   time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time          `db:"updated_at" json:"updated_at"`
}

type Module struct {
	ID                   uuid.UUID       `db:"id" json:"id"`
	CourseID             uuid.UUID       `db:"course_id" json:"course_id"`
	ModuleOrder          int32           `db:"module_order" json:"module_order"`
	Title                string          `db:"title" json:"title"`
	Description          string          `db:"description" json:"description"`
	KeyLearningPoints    json.RawMessage `db:"key_learning_points" json:"key_learning_points"`
	RawModuleOutput      json.RawMessage `db:"raw_module_output" json:"raw_module_output"`
	RawLessonsPlanOutput json.RawMessage `db:"raw_lessons_plan_output" json:"raw_lessons_plan_output"`
	CreatedAt            time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt            time.Time       `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID        uuid.UUID `db:"id" json:"id"`
	Username  string    `db:"username" json:"username"`
	Password  string    `db:"password" json:"password"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}
