// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: modules.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createModule = `-- name: CreateModule :one
INSERT INTO modules (
  id,
  course_id,
  module_order,
  title,
  description,
  key_learning_points,
  raw_lessons_plan_output,
  created_at,
  updated_at
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6::jsonb,
  $7::jsonb,
  $8,
  $9
)
RETURNING
  id,
  course_id,
  module_order,
  title,
  description,
  key_learning_points,
  raw_module_output,
  raw_lessons_plan_output,
  created_at,
  updated_at
`

type CreateModuleParams struct {
	ID                   uuid.UUID       `db:"id" json:"id"`
	CourseID             uuid.UUID       `db:"course_id" json:"course_id"`
	ModuleOrder          int32           `db:"module_order" json:"module_order"`
	Title                string          `db:"title" json:"title"`
	Description          string          `db:"description" json:"description"`
	KeyLearningPoints    json.RawMessage `db:"key_learning_points" json:"key_learning_points"`
	RawLessonsPlanOutput json.RawMessage `db:"raw_lessons_plan_output" json:"raw_lessons_plan_output"`
	CreatedAt            time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt            time.Time       `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateModule(ctx context.Context, arg CreateModuleParams) (Module, error) {
	row := q.db.QueryRow(ctx, createModule,
		arg.ID,
		arg.CourseID,
		arg.ModuleOrder,
		arg.Title,
		arg.Description,
		arg.KeyLearningPoints,
		arg.RawLessonsPlanOutput,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Module
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.ModuleOrder,
		&i.Title,
		&i.Description,
		&i.KeyLearningPoints,
		&i.RawModuleOutput,
		&i.RawLessonsPlanOutput,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

type CreateModulesParams struct {
	ID                   uuid.UUID       `db:"id" json:"id"`
	CourseID             uuid.UUID       `db:"course_id" json:"course_id"`
	ModuleOrder          int32           `db:"module_order" json:"module_order"`
	Title                string          `db:"title" json:"title"`
	Description          string          `db:"description" json:"description"`
	KeyLearningPoints    json.RawMessage `db:"key_learning_points" json:"key_learning_points"`
	RawLessonsPlanOutput json.RawMessage `db:"raw_lessons_plan_output" json:"raw_lessons_plan_output"`
	CreatedAt            time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt            time.Time       `db:"updated_at" json:"updated_at"`
}

const deleteModuleByID = `-- name: DeleteModuleByID :execrows
DELETE FROM modules
WHERE id = $1
`

func (q *Queries) DeleteModuleByID(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteModuleByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getModuleByID = `-- name: GetModuleByID :one
SELECT
  id,
  course_id,
  module_order,
  title,
  description,
  key_learning_points,
  raw_module_output,
  raw_lessons_plan_output,
  created_at,
  updated_at
FROM modules
WHERE id = $1
`

func (q *Queries) GetModuleByID(ctx context.Context, id uuid.UUID) (Module, error) {
	row := q.db.QueryRow(ctx, getModuleByID, id)
	var i Module
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.ModuleOrder,
		&i.Title,
		&i.Description,
		&i.KeyLearningPoints,
		&i.RawModuleOutput,
		&i.RawLessonsPlanOutput,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listModulesByCourseID = `-- name: ListModulesByCourseID :many
SELECT
  id,
  course_id,
  module_order,
  title,
  description,
  key_learning_points,
  raw_module_output,
  raw_lessons_plan_output,
  created_at,
  updated_at
FROM modules
WHERE course_id = $1
ORDER BY module_order ASC, id ASC
`

func (q *Queries) ListModulesByCourseID(ctx context.Context, courseID uuid.UUID) ([]Module, error) {
	rows, err := q.db.Query(ctx, listModulesByCourseID, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Module{}
	for rows.Next() {
		var i Module
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.ModuleOrder,
			&i.Title,
			&i.Description,
			&i.KeyLearningPoints,
			&i.RawModuleOutput,
			&i.RawLessonsPlanOutput,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModulesByCourseIDs = `-- name: ListModulesByCourseIDs :many
SELECT
  id,
  course_id,
  module_order,
  title,
  description,
  key_learning_points,
  raw_module_output,
  raw_lessons_plan_output,
  created_at,
  updated_at
FROM modules
WHERE course_id = ANY($1::uuid[])
ORDER BY course_id ASC, module_order ASC, id ASC
`

func (q *Queries) ListModulesByCourseIDs(ctx context.Context, courseIds []uuid.UUID) ([]Module, error) {
	rows, err := q.db.Query(ctx, listModulesByCourseIDs, courseIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Module{}
	for rows.Next() {
		var i Module
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.ModuleOrder,
			&i.Title,
			&i.Description,
			&i.KeyLearningPoints,
			&i.RawModuleOutput,
			&i.RawLessonsPlanOutput,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateModule = `-- name: UpdateModule :one
UPDATE modules
SET
  course_id = $1,
  module_order = $2,
  title = $3,
  description = $4,
  key_learning_points = $5::jsonb,
  raw_lessons_plan_output = $6::jsonb,
  updated_at = $7
WHERE id = $8
RETURNING
  id,
  course_id,
  module_order,
  title,
  description,
  key_learning_points,
  raw_module_output,
  raw_lessons_plan_output,
  created_at,
  updated_at
`

type UpdateModuleParams struct {
	CourseID             uuid.UUID       `db:"course_id" json:"course_id"`
	ModuleOrder          int32           `db:"module_order" json:"module_order"`
	Title                string          `db:"title" json:"title"`
	Description          string          `db:"description" json:"description"`
	KeyLearningPoints    json.RawMessage `db:"key_learning_points" json:"key_learning_points"`
	RawLessonsPlanOutput json.RawMessage `db:"raw_lessons_plan_output" json:"raw_lessons_plan_output"`
	UpdatedAt            time.Time       `db:"updated_at" json:"updated_at"`
	ID                   uuid.UUID       `db:"id" json:"id"`
}

func (q *Queries) UpdateModule(ctx context.Context, arg UpdateModuleParams) (Module, error) {
	row := q.db.QueryRow(ctx, updateModule,
		arg.CourseID,
		arg.ModuleOrder,
		arg.Title,
		arg.Description,
		arg.KeyLearningPoints,
		arg.RawLessonsPlanOutput,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Module
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.ModuleOrder,
		&i.Title,
		&i.Description,
		&i.KeyLearningPoints,
		&i.RawModuleOutput,
		&i.RawLessonsPlanOutput,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
