// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ownership.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const ownsCourse = `-- name: OwnsCourse :one
SELECT EXISTS (
  SELECT 1
  FROM courses course
  WHERE course.id = $1 AND course.clerk_user_id = $2
)
`

type OwnsCourseParams struct {
	ID          uuid.UUID `db:"id" json:"id"`
	ClerkUserID string    `db:"clerk_user_id" json:"clerk_user_id"`
}

func (q *Queries) OwnsCourse(ctx context.Context, arg OwnsCourseParams) (bool, error) {
	row := q.db.QueryRow(ctx, ownsCourse, arg.ID, arg.ClerkUserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const ownsGenerationJob = `-- name: OwnsGenerationJob :one
SELECT EXISTS (
  SELECT 1
  FROM generation_jobs job
  JOIN generation_requests request ON request.id = job.request_id
  WHERE job.id = $1 AND request.clerk_user_id = $2
)
`

type OwnsGenerationJobParams struct {
	ID          uuid.UUID `db:"id" json:"id"`
	ClerkUserID string    `db:"clerk_user_id" json:"clerk_user_id"`
}

func (q *Queries) OwnsGenerationJob(ctx context.Context, arg OwnsGenerationJobParams) (bool, error) {
	row := q.db.QueryRow(ctx, ownsGenerationJob, arg.ID, arg.ClerkUserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const ownsGenerationRequest = `-- name: OwnsGenerationRequest :one
SELECT EXISTS (
  SELECT 1 FROM generation_requests
  WHERE id = $1 AND clerk_user_id = $2
)
`

type OwnsGenerationRequestParams struct {
	ID          uuid.UUID `db:"id" json:"id"`
	ClerkUserID string    `db:"clerk_user_id" json:"clerk_user_id"`
}

func (q *Queries) OwnsGenerationRequest(ctx context.Context, arg OwnsGenerationRequestParams) (bool, error) {
	row := q.db.QueryRow(ctx, ownsGenerationRequest, arg.ID, arg.ClerkUserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const ownsLesson = `-- name: OwnsLesson :one
SELECT EXISTS (
  SELECT 1
  FROM lessons lesson
  JOIN modules module ON module.id = lesson.module_id
  JOIN courses course ON course.id = module.course_id
  WHERE lesson.id = $1 AND course.clerk_user_id = $2
)
`

type OwnsLessonParams struct {
	ID          uuid.UUID `db:"id" json:"id"`
	ClerkUserID string    `db:"clerk_user_id" json:"clerk_user_id"`
}

func (q *Queries) OwnsLesson(ctx context.Context, arg OwnsLessonParams) (bool, error) {
	row := q.db.QueryRow(ctx, ownsLesson, arg.ID, arg.ClerkUserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const ownsModule = `-- name: OwnsModule :one
SELECT EXISTS (
  SELECT 1
  FROM modules module
  JOIN courses course ON course.id = module.course_id
  WHERE module.id = $1 AND course.clerk_user_id = $2
)
`

type OwnsModuleParams struct {
	ID          uuid.UUID `db:"id" json:"id"`
	ClerkUserID string    `db:"clerk_user_id" json:"clerk_user_id"`
}

func (q *Queries) OwnsModule(ctx context.Context, arg OwnsModuleParams) (bool, error) {
	row := q.db.QueryRow(ctx, ownsModule, arg.ID, arg.ClerkUserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
