// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CountCourses(ctx context.Context, arg CountCoursesParams) (int64, error)
	CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error)
	CreateGenerationRequest(ctx context.Context, arg CreateGenerationRequestParams) (GenerationRequest, error)
	CreateLesson(ctx context.Context, arg CreateLessonParams) (Lesson, error)
	CreateLessonExercise(ctx context.Context, arg CreateLessonExerciseParams) (LessonExercise, error)
	CreateLessonExercises(ctx context.Context, arg []CreateLessonExercisesParams) (int64, error)
	CreateLessonQuiz(ctx context.Context, arg CreateLessonQuizParams) (LessonQuiz, error)
	CreateLessonQuizzes(ctx context.Context, arg []CreateLessonQuizzesParams) (int64, error)
	CreateLessons(ctx context.Context, arg []CreateLessonsParams) (int64, error)
	CreateModule(ctx context.Context, arg CreateModuleParams) (Module, error)
	CreateModules(ctx context.Context, arg []CreateModulesParams) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCourseByID(ctx context.Context, arg DeleteCourseByIDParams) (int64, error)
	DeleteCourseByRequestID(ctx context.Context, arg DeleteCourseByRequestIDParams) (int64, error)
	DeleteLessonByID(ctx context.Context, arg DeleteLessonByIDParams) (int64, error)
	DeleteLessonExercisesByLessonID(ctx context.Context, arg DeleteLessonExercisesByLessonIDParams) error
	DeleteLessonQuizzesByLessonID(ctx context.Context, arg DeleteLessonQuizzesByLessonIDParams) error
	DeleteModuleByID(ctx context.Context, arg DeleteModuleByIDParams) (int64, error)
	DeleteUserByID(ctx context.Context, arg DeleteUserByIDParams) (int64, error)
	GetCourseByID(ctx context.Context, arg GetCourseByIDParams) (Course, error)
	GetCourseByRequestID(ctx context.Context, arg GetCourseByRequestIDParams) (Course, error)
	GetGenerationRequestByCourseID(ctx context.Context, arg GetGenerationRequestByCourseIDParams) (GenerationRequest, error)
	GetGenerationRequestByID(ctx context.Context, arg GetGenerationRequestByIDParams) (GenerationRequest, error)
	GetGenerationStatusByID(ctx context.Context, arg GetGenerationStatusByIDParams) (GetGenerationStatusByIDRow, error)
	GetLessonByID(ctx context.Context, arg GetLessonByIDParams) (Lesson, error)
	GetModuleByID(ctx context.Context, arg GetModuleByIDParams) (Module, error)
	GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error)
	GetUserByUsername(ctx context.Context, arg GetUserByUsernameParams) (User, error)
	IsCourseContentComplete(ctx context.Context, arg IsCourseContentCompleteParams) (*bool, error)
	ListCoursesCreatedAtAsc(ctx context.Context, arg ListCoursesCreatedAtAscParams) ([]Course, error)
	ListCoursesCreatedAtDesc(ctx context.Context, arg ListCoursesCreatedAtDescParams) ([]Course, error)
	ListCoursesStatusAsc(ctx context.Context, arg ListCoursesStatusAscParams) ([]Course, error)
	ListCoursesStatusDesc(ctx context.Context, arg ListCoursesStatusDescParams) ([]Course, error)
	ListCoursesTitleAsc(ctx context.Context, arg ListCoursesTitleAscParams) ([]Course, error)
	ListCoursesTitleDesc(ctx context.Context, arg ListCoursesTitleDescParams) ([]Course, error)
	ListCoursesUpdatedAtAsc(ctx context.Context, arg ListCoursesUpdatedAtAscParams) ([]Course, error)
	ListCoursesUpdatedAtDesc(ctx context.Context, arg ListCoursesUpdatedAtDescParams) ([]Course, error)
	ListLessonExercisesByLessonID(ctx context.Context, arg ListLessonExercisesByLessonIDParams) ([]LessonExercise, error)
	ListLessonExercisesByLessonIDs(ctx context.Context, arg ListLessonExercisesByLessonIDsParams) ([]LessonExercise, error)
	ListLessonQuizzesByLessonID(ctx context.Context, arg ListLessonQuizzesByLessonIDParams) ([]LessonQuiz, error)
	ListLessonQuizzesByLessonIDs(ctx context.Context, arg ListLessonQuizzesByLessonIDsParams) ([]LessonQuiz, error)
	ListLessonsByModuleID(ctx context.Context, arg ListLessonsByModuleIDParams) ([]Lesson, error)
	ListLessonsByModuleIDs(ctx context.Context, arg ListLessonsByModuleIDsParams) ([]Lesson, error)
	ListModulesByCourseID(ctx context.Context, arg ListModulesByCourseIDParams) ([]Module, error)
	ListModulesByCourseIDs(ctx context.Context, arg ListModulesByCourseIDsParams) ([]Module, error)
	ReplaceLessonContent(ctx context.Context, arg ReplaceLessonContentParams) (Lesson, error)
	UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error)
	UpdateGenerationRequest(ctx context.Context, arg UpdateGenerationRequestParams) (GenerationRequest, error)
	UpdateLesson(ctx context.Context, arg UpdateLessonParams) (Lesson, error)
	UpdateModule(ctx context.Context, arg UpdateModuleParams) (Module, error)
}

var _ Querier = (*Queries)(nil)
